using Nop.Services.Localization;

namespace Nxg.Web.Framework.Migrations.CustomLocalizations.Localizations;

public class PortugueseLocalization : ICustomLocalization
{
    public string UniqueSeoCode => "pt";

    public Dictionary<string, string> GetTerms()
    {
        return new Dictionary<string, string>
        {
            ["generic.payment.provider.redirection.url.issue"] =
                "O URL de redirecionamento do provedor de pagamento veio vazio.",
            ["Configuration.Settings.UserJourney.MinutesApartToShowAlert"] = "Minutos de limite de alerta automático",
            ["Configuration.Settings.UserJourney.MinutesApartToShowAlert.Hint"] =
                "Quando o usuário é empurrado para um slot maior que esse valor em minutos, mostramos um alerta",
            ["Admin.Configuration.Settings.UserJourney.MinutesApartToShowAlert"] =
                "Minutos de limite de alerta automático",
            ["Admin.Configuration.Settings.UserJourney.MinutesApartToShowAlert.Hint"] =
                "Quando o usuário é empurrado para um slot maior que esse valor em minutos, mostramos um alerta",
            ["Admin.Configuration.Settings.UserJourney.AutomaticallyPushUsersToNextAvailableSlot"] =
                "Empurrar usuários para o próximo slot disponível",
            ["Admin.Configuration.Settings.UserJourney.AutomaticallyPushUsersToNextAvailableSlot.Hint"] =
                "Se ativado: quando o slot expirar, se um usuário fizer uma ação no sistema, tentaremos levá-lo para o próximo slot disponível, se possível, sem interromper a jornada ",
            ["admin.configuration.stores.fields.storenumber"] = "Número da Loja",
            ["Account.AccountRemoved"] = "Sua conta foi removida",
            ["Account.AccountRemoved.Explanation"] =
                "Você não poderá mais fazer login a partir desta conta ou realizar qualquer ação com ela.",
            ["Account.AddressBook"] = "Catálogo de Endereços",
            ["Account.AddressBook.ViewEditAddresses"] = "Visualizar/editar endereços",
            ["Account.AddressDetails"] = "Detalhes do endereço",
            ["Account.Back"] = "Voltar",
            ["Account.ConfirmNewPassword"] = "Redigite sua nova senha",
            ["Account.CustomerAddresses.AddressDetails"] = "Detalhes do endereço",
            ["Account.CustomerAddresses.DefaultAddress"] = "Usar como endereço padrão",
            ["Account.CustomerAddresses.NoDefaultAddress"] = "Ainda não há endereços, adicione um abaixo.",
            ["Account.CustomerOrders.PreviousOrders"] = "Pedidos anteriores",
            ["Account.CustomerVehicle.NoVehicles"] = "Sem veículos",
            ["Account.CustomerVehicles.DefaultVehicle"] = "Usar como veículo padrão",
            ["Account.CustomerVehicles.VehicleDetails"] = "Detalhes do veículo",
            ["Account.DeleteAccount"] = "Apagar conta",
            ["Account.DeleteAccount"] = "Excluir conta",
            ["Account.DeleteAccount.Explanation"] =
                "Isto excluirá sua conta de nosso sistema e você não poderá mais fazer login.",
            ["Account.DeleteAccount.FailedToDelete"] = "Falha ao excluir a conta, verifique se sua senha está correta.",
            ["Account.DeleteAccount.Instructions"] =
                "Para excluir sua conta, confirme sua senha primeiro para que possamos confirmar sua identidade.",
            ["Account.ForgotPassword.button"] = "Recuperar senha",
            ["Account.ForgotPassword.label"] = "Digite o endereço de e-mail associado à sua conta",
            ["Account.ForgotPassword.label.AutoCreated"] =
                "Como parte das medidas de segurança aprimoradas, você deve redefinir sua senha. Isso também significa que todos os pedidos anteriores não serão mais visíveis na página Contas (embora novos pedidos o sejam). \r\n\r\nDigite o endereço de e-mail associado à sua conta",
            ["Account.Forgotyourpassword"] = "Esqueceu sua senha?",
            ["Account.Forgotyourpassword.AutoCreated"] = "Redefinir sua senha",
            ["Account.Login.DontHaveAnAccount"] = "Não tem uma conta?",
            ["Account.Login.DontHaveAnAccount.FiveguysES"] = "Não tem uma conta no Five Guys?",
            ["Account.Login.DontHaveAnAccount.FiveguysUK"] = "Não tem uma conta no Five Guys?",
            ["Account.Login.DontHaveAnAccount.FiveguysDE"] = "Não tem uma conta no Five Guys?",
            ["Account.Login.RememberMe"] = "Lembra-se de mim?",
            ["Account.Login.RememberMe.FiveguysES"] = "Lembre-se de mim na próxima vez",
            ["Account.Login.RememberMe.FiveguysUK"] = "Lembre-se de mim na próxima vez",
            ["Account.Login.RememberMe.FiveguysDE"] = "Lembre-se de mim na próxima vez",
            ["Account.Login.RememberMe.warning"] =
                "Ative este recurso apenas se tiver certeza de que seu dispositivo possui uma senha forte e está protegido contra acesso não autorizado.",
            ["Account.Login.Welcome.Custom"] = "Login",
            ["Account.Login.Welcome.Custom.FiveguysES"] = "Faça login para editar sua conta",
            ["Account.Login.Welcome.Custom.FiveguysUK"] = "Faça login para editar sua conta",
            ["Account.Login.Welcome.Custom.FiveguysDE"] = "Faça login para editar sua conta",
            ["Account.Login.Welcome.FiveguysES"] = "Bem-vindo de volta",
            ["Account.Login.Welcome.FiveguysUK"] = "Bem-vindo de volta",
            ["Account.Login.Welcome.FiveguysDE"] = "Bem-vindo de volta",
            ["Account.Login.Welcome.GO.Custom"] = "Você deve estar logado para iniciar um novo pedido de grupo.",
            ["Account.Login.WrongCredentials.AutoCreatedAccount.part1"] =
                "Você deve redefinir sua senha antes de continuar. Por favor ",
            ["Account.Login.WrongCredentials.AutoCreatedAccount.part2"] = "clique aqui ",
            ["Account.Login.WrongCredentials.AutoCreatedAccount.part3"] = "para redefinir sua senha.",
            ["Account.Marketing"] = "Marketing",
            ["Account.Marketing.SendMe"] = "Envie-me ótimas ofertas e notícias relevantes.",
            ["Account.Marketing.SendMe.FiveguysES"] =
                "Envie-me ótimas ofertas e notícias relevantes sobre o Five Guys.",
            ["Account.Marketing.SendMe.FiveguysUK"] =
                "Envie-me ótimas ofertas e notícias relevantes sobre o Five Guys.",
            ["Account.Marketing.SendMe.FiveguysDE"] =
                "Envie-me ótimas ofertas e notícias relevantes sobre o Five Guys.",
            ["Account.MyAccount"] = "Minha conta",
            ["Account.MyAccount.Login"] = "Login",
            ["Account.MyAccount.WeMissedYou"] = "Sentimos sua falta.",
            ["Account.MyAccount.Welcomeback"] = "Bem-vindo de volta",
            ["Account.NewPassword"] = "Digite sua nova senha",
            ["Account.OldPassword"] = "Digite sua senha atual",
            ["Account.Orders"] = "Pedidos",
            ["Account.PasswordRecovery.RecoverButton.AutoCreated"] = "Redefinir sua senha",
            ["Account.RecoverPassword.Instructions"] =
                "Um e-mail foi enviado a você com um link para redefinir sua senha. Verifique sua pasta de spam se não receber o e-mail em breve.",
            ["Account.Register.Warning"] =
                "Usamos as informações que você nos forneceu aqui para processar seu pedido. Para obter mais informações sobre como e por que usamos essas informações, consulte nossa política de privacidade.",
            ["Account.Register.Warning.FiveguysES"] =
                "Usamos as informações que você nos forneceu aqui para processar seu pedido. Para saber mais informações sobre como e por que usamos essas informações, consulte nosso <a target=\"_blank \" href=\"https://fiveguys.co.uk/privacy-policy/\">Política de Privacidade</a>",
            ["Account.Register.Warning.FiveguysUK"] =
                "Usamos as informações que você nos forneceu aqui para processar seu pedido. Para saber mais informações sobre como e por que usamos essas informações, consulte nosso <a target=\"_blank \" href=\"https://fiveguys.co.uk/privacy-policy/\">Política de Privacidade</a>",
            ["Account.Register.Warning.FiveguysDE"] =
                "Usamos as informações que você nos forneceu aqui para processar seu pedido. Para saber mais informações sobre como e por que usamos essas informações, consulte nosso <a target=\"_blank \" href=\"https://fiveguys.co.uk/privacy-policy/\">Política de Privacidade</a>",
            ["Account.RemoveAddress"] = "Remover endereço?",
            ["Account.RemoveCard"] = "Remover cartão",
            ["Account.RemoveVehicle"] = "Remover Veículo",
            ["Account.SavedCards"] = "Cartões Guardados",
            ["Account.SavedCards.BlockSaveCardAutomatically"] = "Não salvar cartões em minha conta",
            ["Account.SavedCards.Card"] = "Cartão: ",
            ["Account.SavedCards.Expiry"] = "Expiração: ",
            ["Account.SavedCards.NoCards"] = "Nenhum cartão salvo até agora.",
            ["Account.SavedCards.StoreSavedAgainst"] = "Salvo para loja: ",
            ["Account.SavedCards.ViewSavedCards"] = "Ver cartões",
            ["Account.Security"] = "Segurança",
            ["Account.VehicleDetails"] = "Detalhes do veículo",
            ["Account.VehicleDetails.NoVehicles"] = "Ainda não há veículos, adicione um abaixo.",
            ["Account.VehicleDetails.ViewEditVehicles"] = "Ver / Editar Veículos",
            ["Account.View"] = "Visualizar",
            ["Account.ViewPreviousOrders"] = "Pedidos anteriores",
            ["Account.YourAddresses"] = "Meus endereços",
            ["Account.YourCards"] = "Meus cartões salvos",
            ["Account.YourDetails"] = "Seus detalhes",
            ["Account.YourLast"] = "Seu último",
            ["Account.YourVehicles"] = "Detalhes do veículo",
            ["ActivityLog.AddNewEmailConfiguration"] = "Uma nova configuração de e-mail foi criada (ID = {0})",
            ["ActivityLog.AddNewMGS"] = "Um novo seletor de grupo modificador foi criado: {0}",
            ["ActivityLog.AddNewSpa"] = "A nova disponibilidade programada de produto foi adicionada",
            ["ActivityLog.DeleteCustomerAccount"] = "Cliente excluiu sua conta (ID = {0})",
            ["ActivityLog.DeleteEmailConfiguration"] = "Uma configuração de e-mail foi excluída (ID = {0})",
            ["ActivityLog.EditEmailConfiguration"] = "Uma configuração de e-mail foi atualizada (ID = {0})",
            ["Address.City"] = "Cidade",
            ["Address.Email"] = "E-mail",
            ["Address.Firstname"] = "Nome",
            ["Address.Lastname"] = "Sobrenome",
            ["Address.Phonenumber"] = "Número de telefone",
            ["Address.Streetaddress1"] = "Endereço 1",
            ["Address.Streetaddress2"] = "Endereço 2",
            ["Address.ZipPostalCode"] = "CEP / Código Postal",
            ["Admin.Catalog.Attributes.ProductAttributes.Fields.IncludeInNoToppingsModalCheck"] =
                "Incluir estes modificadores na verificação do modal 'Sem coberturas'",
            ["Admin.Catalog.Attributes.ProductAttributes.Fields.IncludeInNoToppingsModalCheck.Hint"] =
                "Modificadores deste tipo de atributo de produto serão verificados se algum for selecionado na ação adicionar ao pedido, caso contrário, o modal 'Sem coberturas' será exibido. ",
            ["Admin.Catalog.Attributes.ProductAttributes.Fields.ShowProductInformationButton"] =
                "Mostrar botão de informações do produto nos valores de atributo",
            ["Admin.Catalog.Attributes.ProductAttributes.Fields.ShowProductInformationButton.Hint"] =
                "Um botão em cada valor de atributo que abre uma janela pop-up quando clicado, contendo as informações nutricionais do atributo.",
            ["Admin.Catalog.Attributes.ProductAttributes.Fields.MaxSelectedAttributeCount"] =
                "Número máximo de valores de atributos que podem ser selecionados",
            ["Admin.Catalog.Attributes.ProductAttributes.Fields.MaxSelectedAttributeCount.Hint"] =
                "O número máximo de valores de atributos que podem ser selecionados para este atributo",
            ["Admin.Catalog.Attributes.ProductAttributes.Fields.MinSelectedAttributeCount"] =
                "Número mínimo de valores de atributos que podem ser selecionados",
            ["Admin.Catalog.Attributes.ProductAttributes.Fields.MinSelectedAttributeCount.Hint"] =
                "O número mínimo de valores de atributos que podem ser selecionados para este atributo",
            ["Admin.Catalog.Delivery.DeliveryTimings.BackToStore"] = "voltar à entrega",
            ["Admin.Catalog.Delivery.DeliveryTimings.EditDeliveryTimingsDetails"] =
                "Editar detalhes do tempo de entrega",
            ["Admin.Catalog.Delivery.DeliveryTimings.SelectBeforeEdit"] = "Selecione primeiro os dias de entrega",
            ["Admin.Catalog.KitchenCapacity.Timings.Alert.AddNew"] = "Todos os campos são obrigatórios.",
            ["Admin.Catalog.KitchenCapacity.editkitchencapacitydetails"] = "Editar detalhes da capacidade da cozinha",
            ["Admin.Catalog.MGS.AddedSuccessfully"] = "Seletor de grupo de modificadores criado com sucesso",
            ["Admin.Catalog.MGS.Fields.CreatedOnUTC"] = "Criado em",
            ["Admin.Catalog.MGS.Fields.DisplayName"] = "Nome de exibição (face do cliente)",
            ["Admin.Catalog.MGS.Fields.Name"] = "Nome",
            ["Admin.Catalog.MGS.Fields.Products"] = "Produtos",
            ["Admin.Catalog.MGS.Fields.ProductsModifiers"] = "Modificadores",
            ["Admin.Catalog.MGS.UpdatedSuccessfully"] =
                "O seletor do grupo de modificadores foi atualizado com sucesso",
            ["Admin.Catalog.MSG.AddButton"] = "Adicionar seletor de grupo de modificadores",
            ["Admin.Catalog.Products.Fields.Allergens"] = "Alérgenos",
            ["Admin.Catalog.Products.Fields.FixedQuantitiesSKU"] = "SKU de quantidades fixas",
            ["Admin.Catalog.Products.Fields.FixedQuantitiesSKU.Hint"] =
                "SKU completo incluindo propriedades de quantidades fixas",
            ["Admin.Catalog.Products.Fields.Nutrition"] = "Nutrição",
            ["Admin.Catalog.Products.Fields.RestrictedStores"] = "Lojas",
            ["Admin.Catalog.Products.Fields.RestrictedStores.Hint"] =
                "Opção para restringir/remover este produto para/de determinadas lojas. " +
                "Se você tiver várias lojas, escolha uma ou várias da lista. " +
                " Se não utilizar esta opção basta deixar este campo em branco." +
                "Para utilizar esta funcionalidade terá de desactivar a seguinte configuração: " +
                "Configuração > Definições do catálogo > Ignorar regras de \"limite por loja\" ( em todo o site).",
            ["Admin.Catalog.Products.Fields.StoreRestrictionMode"] = "Modo restrito",
            ["Admin.Catalog.Products.Fields.VariantDisplayType"] = "Variant display type",
            ["Admin.Catalog.Products.Fields.VariantDisplayType.Hint"] =
                "How the variants will be presented in the grouped product page (buttons, checkboxes)",
            ["Admin.Catalog.Products.ProductOrderTypeMapping"] = "Tipos de pedidos disponíveis",
            ["Admin.Catalog.Products.ProductOrderTypeMapping.AddNew"] = "Adicionar novo mapeamento de tipo de pedido",
            ["Admin.Catalog.Products.ProductOrderTypeMapping.Fields.OrderType"] = "Tipo de pedido",
            ["Admin.Catalog.Products.ProductOrderTypeMapping.Fields.Store"] = "Loja",
            ["Admin.Catalog.Products.ProductOrderTypeMapping.Hint"] =
                "Especificar para qual tipo de pedido (e opcionalmente armazenar) este produto está disponível",
            ["Admin.Catalog.Products.ProductPerOrderType"] = "Tipos de Pedidos",
            ["Admin.Catalog.Products.TierPrices.Fields.OrderType"] = "Tipo de pedido",
            ["Admin.Catalog.Products.Variants.DisplayType.Buttons"] = "Buttons",
            ["Admin.Catalog.Products.Variants.DisplayType.Checkboxes"] = "Checkboxes",
            ["Admin.Catalog.Store.Holiday.Alert.HolidayAdd"] = "Falha ao adicionar feriado.",
            ["Admin.Catalog.Store.Holiday.SaveBeforeEdit"] =
                "Você precisa salvar a loja antes de adicionar feriados a esta página da loja.",
            ["Admin.Catalog.Store.LargeOrderNotification.SaveBeforeEdit"] =
                "Você precisa salvar a loja antes de adicionar notificações de pedidos grandes para esta página da loja.",
            ["Admin.Catalog.Store.PreOrderNotification.SaveBeforeEdit"] =
                "Você precisa salvar a loja antes de poder adicionar notificações de pré-encomenda para esta página da loja.",
            ["Admin.Catalog.Store.StoreTimings.EditStoreTimingsDetails"] = "Editar detalhes de horários da loja",
            ["Admin.Catalog.Store.Timings.Alert.TimingsAdd"] = "Falha ao adicionar horário de abertura e fechamento.",
            ["Admin.Catalog.Store.Timings.SaveBeforeEdit"] =
                "Você precisa salvar a loja antes de adicionar horários para esta página da loja.",
            ["Admin.Config.UserJourney.Cart"] = "Página da seção do carrinho",
            ["Admin.Config.UserJourney.CheckoutPage"] = "Página de check-out",
            ["Admin.Config.UserJourney.Homepage"] = "Página inicial",
            ["Admin.Config.UserJourney.MenuPage"] = "Página de menu",
            ["Admin.Config.UserJourney.ProcessingPaymentPage"] = "Página de pagamento em processamento",
            ["Admin.Config.UserJourney.ProductPage"] = "Página do produto",
            ["Admin.Config.UserJourney.StoreSelection"] = "Página de seleção de loja",
            ["Admin.Config.UserJourney.TimeSlotSelectionPage"] = "Time Slot Selection Page",
            ["Admin.Configuration.AppSettings.DistributedCache.Prefix"] = "Prefixo para chaves redis",
            ["Admin.Configuration.AppSettings.DistributedCache.Prefix.Hint"] =
                "Prefixo de string que queremos colocar nas chaves redis para que não colida com outros ambientes usando a mesma instância redis",
            ["Admin.Configuration.Catalog.MenuManager"] = "Editor do gerenciador de menus",
            ["Admin.Configuration.Catalog.ModifiersGroupSelector"] = "Seletor de grupo de modificadores",
            ["Admin.Configuration.Customers.ImportFromCsv"] = "Importar clientes de CSV",
            ["Admin.Configuration.Delivery.BlockTitle.DeliveryTimings"] = "Horário de entrega",
            ["Admin.Configuration.Delivery.BlockTitle.SelectDay"] = "Selecionar dias de entrega",
            ["Admin.Configuration.Delivery.DeletedTiming"] = "O prazo de entrega foi excluído com sucesso.",
            ["Admin.Configuration.Delivery.DeliveryDetails"] = "Detalhes da entrega",
            ["Admin.Configuration.Delivery.UpdatedTiming"] = "O prazo de entrega foi atualizado com sucesso.",
            ["Admin.Configuration.DineIn"] = "Refeições",
            ["Admin.Configuration.DineIn.BackToDineIn"] = "Voltar para jantar em casa",
            ["Admin.Configuration.DineIn.IsDineInEnabled"] = "Ativado?",
            ["Admin.Configuration.DineIn.QRCodeForStore"] = "QR Code da loja: ",
            ["Admin.Configuration.DineIn.QRcode"] = "Código QR",
            ["Admin.Configuration.DineIn.Store"] = "Loja",
            ["Admin.Configuration.DineIn.Tables"] = "Mesas",
            ["Admin.Configuration.DineIn.Url"] = "URL",
            ["Admin.Configuration.EmailAccounts.Deleted"] = "A configuração de e-mail foi excluída",
            ["Admin.Configuration.EmailConfiguration"] = "Configuração de e-mail",
            ["Admin.Configuration.EmailConfiguration.BackToList"] = "Voltar à lista de configuração de e-mail",
            ["Admin.Configuration.EmailConfiguration.CreateTitle"] = "Adicionar nova configuração de e-mail",
            ["Admin.Configuration.EmailConfiguration.DisplayName"] = "Nome",
            ["Admin.Configuration.EmailConfiguration.EditTitle"] = "Editar configuração de e-mail",
            ["Admin.Configuration.EmailConfiguration.EmailAddress"] = "Endereço de e-mail",
            ["Admin.Configuration.EmailConfiguration.General"] = "Geral",
            ["Admin.Configuration.GeoLocation.Marketplaces.AddButton"] = "Adicionar mercado",
            ["Admin.Configuration.GeoLocation.Marketplaces.AddNew"] = "Adicionar mercado",
            ["Admin.Configuration.GeoLocation.Marketplaces.AddedSuccessfully"] =
                "O mercado foi adicionado com sucesso.",
            ["Admin.Configuration.GeoLocation.Marketplaces.BackToGeoLocation"] = "voltar à geolocalização",
            ["Admin.Configuration.GeoLocation.Marketplaces.EditAttributeDetails"] = "Editar detalhes do marketplace",
            ["Admin.Configuration.GeoLocation.Marketplaces.Fields.Name.Required"] = "forneça um nome",
            ["Admin.Configuration.GeoLocation.Marketplaces.Link"] = "Link",
            ["Admin.Configuration.GeoLocation.Marketplaces.Logo"] = "Logo",
            ["Admin.Configuration.GeoLocation.Marketplaces.Name"] = "Nome",
            ["Admin.Configuration.GeoLocation.Marketplaces.NotExist"] =
                "Nenhum mercado encontrado com o ID especificado",
            ["Admin.Configuration.GeoLocation.Marketplaces.RadiusDistance"] = "Distância do raio",
            ["Admin.Configuration.GeoLocation.Marketplaces.UnitOfMeasurement"] = "Unidade de medida",
            ["Admin.Configuration.GeoLocation.Marketplaces.UpdatedSuccessfully"] =
                "O marketplace foi atualizado com sucesso.",
            ["Admin.Configuration.KitchenCapacity.Fields.SizeOfSlot"] = "Tamanho do slot (min)",
            ["Admin.Configuration.KitchenCapacity.Fields.SizeOfSlot.hint"] = "Tamanho do slot",
            ["Admin.Configuration.KitchenCapacity.Fields.SlotCapacity"] = "Capacidade do Slot",
            ["Admin.Configuration.KitchenCapacity.Fields.SlotCapacity.hint"] = "Capacidade do slot",
            ["Admin.Configuration.KitchenCapacity.Fields.SlotReservation"] = "Reserva de Slot",
            ["Admin.Configuration.KitchenCapacity.Fields.SlotReservation.hint"] = "Reserva de Slot",
            ["Admin.Configuration.KitchenCapacity.ImportFromCsv"] = "Importar de CSV",
            ["Admin.Configuration.KitchenCapacity.OverlappingConfigurations"] =
                "As alterações de configuração solicitadas se sobrepõem aos horários atuais do dia selecionado. Corrija e tente novamente.",
            ["Admin.Configuration.MGS.NotExist"] = "O seletor de grupo de modificadores não existe",
            ["Admin.Configuration.Settings.Catalog.AllergensAndNutrients"] = "Alérgenos e Nutrientes",
            ["Admin.Configuration.Settings.Catalog.AllergensAndNutrients.Hint"] =
                "Marque para ativar a exibição dos nutrientes e alérgenos do produto",
            ["Admin.Configuration.Settings.Catalog.AllergensAndNutrientsModal"] = "Modal de alergênicos e nutrientes",
            ["Admin.Configuration.Settings.Catalog.AllergensAndNutrientsModal.Hint"] =
                "Verifique a exibição dos nutrientes e alérgenos do produto em um modal em vez de em PDF",
            ["Admin.Configuration.Settings.CustomerUser.AddressFormFields.CityJustForDelivery"] =
                "Ativar configuração de cidade apenas na entrega",
            ["Admin.Configuration.Settings.CustomerUser.AddressFormFields.CityJustForDelivery.Hint"] =
                "Quando marcado significa que a configuração acima só será aplicada a pedidos do tipo entrega.",
            ["Admin.Configuration.Settings.CustomerUser.AddressFormFields.CountryJustForDelivery"] =
                "Ativar configuração de país somente na entrega",
            ["Admin.Configuration.Settings.CustomerUser.AddressFormFields.CountryJustForDelivery.Hint"] =
                "Quando marcado significa que a configuração acima só será aplicada a pedidos do tipo entrega.",
            ["Admin.Configuration.Settings.CustomerUser.AddressFormFields.CountyJustForDelivery"] =
                "Ativar configuração do condado somente na entrega",
            ["Admin.Configuration.Settings.CustomerUser.AddressFormFields.CountyJustForDelivery.Hint"] =
                "Quando marcado significa que a configuração acima só será aplicada a pedidos do tipo entrega.",
            ["Admin.Configuration.Settings.CustomerUser.AddressFormFields.StateProvinceJustForDelivery"] =
                "Ativar configuração de estado/província somente na entrega",
            ["Admin.Configuration.Settings.CustomerUser.AddressFormFields.StateProvinceJustForDelivery.Hint"] =
                "Quando selecionado significa que a configuração acima será aplicada apenas a pedidos do tipo entrega.",
            ["Admin.Configuration.Settings.CustomerUser.AddressFormFields.StreetAddress2JustForDelivery"] =
                "Ativar configuração do endereço 2 apenas na entrega",
            ["Admin.Configuration.Settings.CustomerUser.AddressFormFields.StreetAddress2JustForDelivery.Hint"] =
                "Quando marcado significa que a configuração acima só será aplicada a pedidos do tipo entrega.",
            ["Admin.Configuration.Settings.CustomerUser.AddressFormFields.StreetAddressJustForDelivery"] =
                "Ativar configuração de endereço somente para entrega",
            ["Admin.Configuration.Settings.CustomerUser.AddressFormFields.StreetAddressJustForDelivery.Hint"] =
                "Quando selecionado significa que a configuração acima só será aplicada a pedidos do tipo entrega.",
            ["Admin.Configuration.Settings.CustomerUser.AddressFormFields.ZipPostalCodeJustForDelivery"] =
                "Ativar configuração de CEP apenas na entrega",
            ["Admin.Configuration.Settings.CustomerUser.AddressFormFields.ZipPostalCodeJustForDelivery.Hint"] =
                "Quando marcado significa que a configuração acima só será aplicada a pedidos do tipo entrega.",
            ["Admin.Configuration.Settings.DeliverySettings"] = "Entrega",
            ["Admin.Configuration.Settings.GeneralCommon.BlockTitle.OneTrustCookies"] = "Configurações do One Trust",
            ["Admin.Configuration.Settings.GeneralCommon.CaptchaShowOnGuestCheckoutPage"] =
                "Mostrar na página de checkout do convidado",
            ["Admin.Configuration.Settings.GeneralCommon.CaptchaShowOnGuestCheckoutPage.Hint"] =
                "Marque para mostrar CAPTCHA no check-out do convidado.",
            ["Admin.Configuration.Settings.GeneralCommon.DisplayDefaultFooterItemSettingsModel.DisplayPoweredByLinetenFooterItem"] =
                "Exibir \"Powered by Lineten\"",
            ["Admin.Configuration.Settings.GeneralCommon.DisplayDefaultFooterItemSettingsModel.DisplayPoweredByLinetenFooterItem.Hint"] =
                "Marque para exibir \"Powered by Lineten\" no rodapé",
            ["Admin.Configuration.Settings.GeneralCommon.GoogleApiKey"] = "Chave GoogleApi",
            ["Admin.Configuration.Settings.GeneralCommon.OneTrustScript"] = "One Trust Script",
            ["Admin.Configuration.Settings.GeneralCommon.OneTrustScript.Hint"] =
                "Cole aqui o script One Trust para incorporar neste site",
            ["Admin.Configuration.Settings.GeoLocation.BlockTitle.Marketplaces"] = "MarketPlaces",
            ["Admin.Configuration.Settings.GeoLocation.ClickCollect"] = "Clique e Colete",
            ["Admin.Configuration.Settings.GeoLocation.Curbside"] = "Curbside",
            ["Admin.Configuration.Settings.GeoLocation.Delivery"] = "Entrega",
            ["Admin.Configuration.Settings.GeoLocation.EngineTimeout"] = "Tempo limite do mecanismo (segundos)",
            ["Admin.Configuration.Settings.GeoLocation.UnitMeasurement"] = "Unidade de medida",
            ["Admin.Configuration.Settings.MenuManager"] = "Gerenciador de menus",
            ["Admin.Configuration.Settings.MenuManager.InvalidUrl"] = "URL inválido",
            ["Admin.Configuration.Settings.MenuManager.Url"] = "URL",
            ["Admin.Configuration.Settings.Order.BlockTitle.Type"] = "Tipos de Pedido",
            ["Admin.Configuration.Settings.Order.ClickAndCollectNotes"] = "Clique e colete notas",
            ["Admin.Configuration.Settings.Order.ClickAndCollectNotes.Hint"] =
                "Notas a serem exibidas quando clicar e coletar estiver disponível (deixe em branco se nenhuma nota for exibida).",
            ["Admin.Configuration.Settings.Order.Click_Collect"] = "Clique e Colete",
            ["Admin.Configuration.Settings.Order.Click_CollectEnabled"] = "Clique e Colete",
            ["Admin.Configuration.Settings.Order.Curbside"] = "Curbside",
            ["Admin.Configuration.Settings.Order.CurbsideEnabled"] = "Curbside",
            ["Admin.Configuration.Settings.Order.CurbsideNotes"] = "Notas da calçada",
            ["Admin.Configuration.Settings.Order.CurbsideNotes.Hint"] =
                "Notas a serem exibidas quando a calçada estiver disponível (deixe em branco se nenhuma nota for exibida).",
            ["Admin.Configuration.Settings.Order.Days"] = "Janela de agendamento de coleta (dias)",
            ["Admin.Configuration.Settings.Order.Delivery"] = "Entrega",
            ["Admin.Configuration.Settings.Order.DeliveryEnabled"] = "Entrega",
            ["Admin.Configuration.Settings.Order.DeliveryNotes"] = "Notas de entrega",
            ["Admin.Configuration.Settings.Order.DeliveryNotes.Hint"] =
                "Notas a serem exibidas quando a entrega estiver disponível (deixe em branco se nenhuma nota for exibida).",
            ["Admin.Configuration.Settings.Order.DineInEnabled"] = "Refeições em (mesa)",
            ["Admin.Configuration.Settings.Order.DisplayOrderNotes"] = "Exibir caixa de notas do pedido",
            ["Admin.Configuration.Settings.Order.GroupOrderingEnabled"] = "Ordenação de grupo",
            ["Admin.Configuration.Settings.Order.LeadTimeClickCollectEnabled"] = "Lead Time C&C (min)",
            ["Admin.Configuration.Settings.Order.LeadTimeDineInEnabled"] = "Tempo de Preparação no Local (min)",
            ["Admin.Configuration.Settings.Order.LeadTimeDeliveryEnabled"] = "Tempo de entrega (min)",
            ["Admin.Configuration.Settings.Order.LeadTimeGroupOrder"] = "Pedido de grupo de tempo de entrega (min)",
            ["Admin.Configuration.Settings.Order.MarketPlaceEnabled"] = "Mercados",
            ["Admin.Configuration.Settings.Order.MarketPlaceNotes"] = "Notas do Marketplace",
            ["Admin.Configuration.Settings.Order.MarketPlaceNotes.Hint"] =
                "Notas a serem exibidas quando mercados estiverem disponíveis (deixe em branco se nenhuma nota for exibida).",
            ["Admin.Configuration.Settings.Order.MaxOrderTotalAmount"] = "Valor máximo total do pedido",
            ["Admin.Configuration.Settings.Order.MaxOrderTotalAmount.Hint"] = "Insira o valor total máximo do pedido",
            ["Admin.Configuration.Settings.Order.OrderNotesLength"] = "Comprimento máximo das notas do pedido",
            ["Admin.Configuration.Settings.OrderTypes"] = "Tipos de Pedidos",
            ["Admin.Configuration.Settings.Spa"] = "Disponibilidade programada do produto",
            ["Admin.Configuration.Settings.UserJourney"] = "Jornada do usuário",
            ["Admin.Configuration.Settings.UserJourney.ChangeLocationOnMobile"] =
                "Exibir campo de localização de alteração no celular",
            ["Admin.Configuration.Settings.UserJourney.ChangeLocationOnMobile.Hint"] =
                "Quando ativado, o campo de entrada para a mudança de local é exibido na versão móvel, caso contrário, nada é exibido",
            ["Admin.Configuration.Settings.UserJourney.DisplayDeliveriesAsModal"] =
                "Exibir mercados externos de entrega em um modal",
            ["Admin.Configuration.Settings.UserJourney.DisplayDeliveriesAsModal.Hint"] =
                "Quando ativado, todos os mercados são exibidos em um modal em vez de nos cartões da loja",
            ["Admin.Configuration.Settings.UserJourney.DisplayKCalInModifiers"] = "Exibir kcal em modificadores",
            ["Admin.Configuration.Settings.UserJourney.DisplayKCalInModifiers.Hint"] =
                "Habilitado começa a exibir kcal em modificadores",
            ["Admin.Configuration.Settings.UserJourney.DisplayKCalInProductDescription"] =
                "Display kcal in product's description",
            ["Admin.Configuration.Settings.UserJourney.DisplayKCalInProductDescription.Hint"] =
                "Enabled starts displaying kcal in product's description",
            ["Admin.Configuration.Settings.UserJourney.DisplayKjInProductNutritionInfo"] =
                "Exibir valor kcal / kj nas informações nutricionais do produto",
            ["Admin.Configuration.Settings.UserJourney.DisplayKjInProductNutritionInfo.Hint"] =
                "Exibir o valor kj em conjunto com o valor kcal na primeira linha da tabela de informações nutricionais do produto",
            ["Admin.Configuration.Settings.UserJourney.DisplayKCalInProductDescriptionDisplayType"] =
                "Display type for the product's kcal on the description",
            ["Admin.Configuration.Settings.UserJourney.DisplayMarketingEmailsOption"] =
                "Mostrar seleção de e-mails de marketing",
            ["Admin.Configuration.Settings.UserJourney.DisplayMarketingEmailsOption.Hint"] =
                "Quando ativo no formulário de checkout, os usuários podem selecionar se desejam receber e-mails de marketing",
            ["Admin.Configuration.Settings.UserJourney.DisplayPriceInModifiers"] = "Exibir preços em modificadores",
            ["Admin.Configuration.Settings.UserJourney.DisplayPriceInModifiers.Hint"] =
                "Se ativado na lista de modificadores, o preço será exibido ao lado de cada modificador, se aplicável.",
            ["Admin.Configuration.Settings.UserJourney.HideRadioPriceAdjustment"] = "Ocultar ajuste de preço do rádio",
            ["Admin.Configuration.Settings.UserJourney.HideRadioPriceAdjustment.Hint"] =
                "Quando ativado oculta o ajuste de preço nos modificadores do tipo de rádio",
            ["Admin.Configuration.Settings.UserJourney.HideUpSellsInProductPage"] =
                "Ocultar upsells na página do produto",
            ["Admin.Configuration.Settings.UserJourney.HideUpSellsInProductPage.Hint"] =
                "Ativado ocultará vendas adicionais nas páginas de produtos",
            ["Admin.Configuration.Settings.UserJourney.ModifiersSeparator"] =
                "Separador de modificadores, padrão é <br/> (uma quebra de linha)",
            ["Admin.Configuration.Settings.UserJourney.ModifiersSeparator.Hint"] =
                "Defina como deseja usar para separar os modificadores alguns exemplos: ' | ', ' , ', '<br/>', ' ; ' ",
            ["Admin.Configuration.Settings.UserJourney.NoToppingsModalEnabled"] = "Ative o modal 'Sem coberturas'",
            ["Admin.Configuration.Settings.UserJourney.NoToppingsModalEnabled.Hint"] =
                "Quando ativado, mostra um modal para usuários que não selecionam nenhum modificador no produto",
            ["Admin.Configuration.Settings.UserJourney.OrderTotalWithinButton"] =
                "Fazer com que o total do pedido do produto apareça no botão Adicionar ao pedido.",
            ["Admin.Configuration.Settings.UserJourney.OrderTotalWithinButton.Hint"] =
                "Quando ativado, o total do produto (modificadores incluídos) aparece dentro do botão adicionar ao pedido, caso contrário, ele aparece em uma linha acima dele.",
            ["Admin.Configuration.Settings.UserJourney.ProcessingPaymentPageTimeout"] =
                "Tempo limite no processamento da página do seu pedido (minutos)",
            ["Admin.Configuration.Settings.UserJourney.ProcessingPaymentPageTimeout.Hint"] =
                "Por padrão, o valor é 5 minutos.",
            ["Admin.Configuration.Settings.UserJourney.ProductReviews"] = "Avaliações de produtos",
            ["Admin.Configuration.Settings.UserJourney.ProductReviews.Hint"] =
                "Quando as revisões habilitadas são ativadas e quando as revisões desativadas são desativadas",
            ["Admin.Config.UserJourney.CorporatePage"] = "Página corporativa",
            ["Admin.Configuration.Settings.UserJourney.ShowCorporatePagePopup"] = "Mostrar popup",
            ["Admin.Configuration.Settings.UserJourney.ShowCorporatePagePopup.Hint"] =
                "Mostra um popup ao entrar na página corporativa. Aparece apenas uma vez por sessão",
            ["Admin.Configuration.Settings.UserJourney.CorporatePagePopupContent"] = "Conteúdo do popup",
            ["Admin.Configuration.Settings.UserJourney.CorporatePagePopupContent.Hint"] =
                "Conteúdo do popup (pode ser HTML simples)",
            ["Admin.Configuration.Settings.UserJourney.RecommendedIntakeText"] = "Texto de admissão recomendado",
            ["Admin.Configuration.Settings.UserJourney.ShowAllergensInformationModal"] =
                "Mostrar modal de informações sobre alérgenos",
            ["Admin.Configuration.Settings.UserJourney.ShowAllergensInformationModal.Hint"] =
                "Exibe um modal com informações sobre alérgenos sempre que um usuário acessa a página do menu",
            ["Admin.Configuration.Settings.UserJourney.AllergensInformationModalGuidelineUrl"] =
                "URL da página de diretrizes do modal de informações sobre alérgenos",
            ["Admin.Configuration.Settings.UserJourney.AllergensInformationModalGuidelineUrl.Hint"] =
                "Se este valor for definido, um botão será adicionado ao final do modal.",
            ["Admin.Configuration.Settings.UserJourney.AllowStoreAndTimeslotChange"] = "Botão de alteração da loja",
            ["Admin.Configuration.Settings.UserJourney.AllowStoreAndTimeslotChange.Hint"] =
                "Este botão permite-lhe alterar a loja sem ter de passar pelo processo de seleção de períodos.",
            ["Admin.Configuration.Settings.UserJourney.ShowProductInformationButton"] =
                "Botão de informações do produto",
            ["Admin.Configuration.Settings.UserJourney.ShowProductInformationButton.Hint"] =
                "Um botão em cada cartão de produto que abre uma janela pop-up quando clicado, contendo informações nutricionais do produto.",
            ["Admin.Configuration.Settings.UserJourney.HideCategoryImageInMenuPage"] = "Esconder imagem da categoria",
            ["Admin.Configuration.Settings.UserJourney.HideCategoryImageInMenuPage.Hint"] =
                "Esconder a imagem da categoria no cabeçalho da categoria da página do menu",
            ["Admin.Configuration.Settings.UserJourney.SkipHomePage"] = "Saltar a página inicial",
            ["Admin.Configuration.Settings.UserJourney.SkipHomePage.Hint"] =
                "Se ativado, a página inicial não será exibida. Em vez disso, o usuário será redirecionado para a página localizar meu código postal.",
            ["Admin.Configuration.Settings.UserJourney.SlotDisplayDateTimeFormat"] =
                "Datetime format (override) for the time slot display",
            ["Admin.Configuration.Settings.UserJourney.SlotDisplayDateTimeFormat.Hint"] =
                "When empty we display (today, monday, tuesday, etc.) if you want to display something like (today, monday 1st, tuesday 2nd) add into the format of the date like dddd P. dddd is the week day and P is the day of the month with suffix",
            ["Admin.Configuration.Settings.UserJourney.UseMarketingOptOut"] = "Desativação de marketing",
            ["Admin.Configuration.Settings.UserJourney.UseMarketingOptOut.Hint"] =
                "Ativando marketing como desativação",
            ["Admin.Configuration.Spa.AddButton"] = "Adicionar disponibilidade programada do produto",
            ["Admin.Configuration.Spa.AddNew"] = "Adicionar disponibilidade programada do produto",
            ["Admin.Configuration.Spa.AddedSuccessfully"] = "Nova disponibilidade programada de produto adicionada",
            ["Admin.Configuration.Spa.BackToList"] = "Voltar à lista de disponibilidade agendada de produtos",
            ["Admin.Configuration.Spa.EditAttributeDetails"] =
                "Editar detalhes de disponibilidade do produto programado",
            ["Admin.Configuration.Spa.Fields.CreatedOnUTC"] = "Criado em",
            ["Admin.Configuration.Spa.Fields.DisplayProductWhenNotAvailable"] = "Sempre visível",
            ["Admin.Configuration.Spa.Fields.DisplayProductWhenNotAvailable.Hint"] =
                "Ao habilitar, mesmo que o intervalo de tempo não esteja dentro da disponibilidade programada do produto, o produto será mostrado no menu como indisponível.",
            ["Admin.Configuration.Spa.Fields.Name"] = "Nome",
            ["Admin.Configuration.Spa.Fields.NumberOfAssociatedProducts"] = "Número de produtos",
            ["Admin.Configuration.Spa.Fields.StoreId"] = "Loja",
            ["Admin.Configuration.Spa.NotExist"] =
                "Nenhuma disponibilidade de produto programada encontrada com o id especificado",
            ["Admin.Configuration.Spa.Timings"] = "Tempos de disponibilidade programada do produto",
            ["Admin.Configuration.Spa.Timings.AddButton"] = "Adicionar novo tempo",
            ["Admin.Configuration.Spa.Timings.AddNew"] = "Adicionar novo horário",
            ["Admin.Configuration.Spa.Timings.Alert.AddNew"] = "Todos os campos são obrigatórios.",
            ["Admin.Configuration.Spa.Timings.Alert.TimingsAdd"] =
                "Falha ao adicionar horários de abertura e fechamento.",
            ["Admin.Configuration.Spa.Timings.BackToSpa"] = "Voltar à disponibilidade programada do produto",
            ["Admin.Configuration.Spa.Timings.EditTimingsDetails"] =
                "Editar detalhes do tempo de disponibilidade do produto agendado",
            ["Admin.Configuration.Spa.Timings.Fields.DayId"] = "Dia",
            ["Admin.Configuration.Spa.Timings.Fields.DayIdError"] = "Dia inválido",
            ["Admin.Configuration.Spa.Timings.Fields.EndTime"] = "Hora de término",
            ["Admin.Configuration.Spa.Timings.Fields.EndTimeError"] = "Hora de término inválida",
            ["Admin.Configuration.Spa.Timings.Fields.StartTime"] = "Hora de início",
            ["Admin.Configuration.Spa.Timings.Fields.StartTimeError"] = "Hora de início inválida",
            ["Admin.Configuration.Spa.Timings.SaveBeforeEdit"] =
                "Você precisa salvar a disponibilidade agendada deste produto antes de poder adicionar horários para ele.",
            ["Admin.Configuration.Spa.UpdatedSuccessfully"] =
                "Disponibilidade agendada do produto atualizada com sucesso.",
            ["Admin.Configuration.Stores.AgentCommentLabel"] = "Comentário do agente",
            ["Admin.Configuration.Stores.AgentCommentTitle"] = "Insira uma justificativa abaixo",
            ["Admin.Configuration.Stores.Disabled"] = " foi desativado ",
            ["Admin.Configuration.Stores.Enabled"] = " foi ativado ",
            ["Admin.Configuration.Stores.Fields.Date"] = "Data",
            ["Admin.Configuration.Stores.Fields.Date.hint"] = "Data",
            ["Admin.Configuration.Stores.Fields.DayId"] = "Dia",
            ["Admin.Configuration.Stores.Fields.DayId.hint"] = "Nome do dia",
            ["Admin.Configuration.Stores.Fields.DayIdError"] = "Dia inválido",
            ["Admin.Configuration.Stores.Fields.Disable"] = "Desativar",
            ["Admin.Configuration.Stores.Fields.Enable"] = "Ativar",
            ["Admin.Configuration.Stores.Fields.EnableDisableStore"] = "Loja habilitada",
            ["Admin.Configuration.Stores.Fields.EndTime"] = "Hora de término",
            ["Admin.Configuration.Stores.Fields.EndTime.hint"] = "Hora de término",
            ["Admin.Configuration.Stores.Fields.EndTimeError"] = "Hora de término inválida",
            ["Admin.Configuration.Stores.Fields.Friday"] = "Sexta-feira",
            ["Admin.Configuration.Stores.Fields.Friday.hint"] = "Sexta-feira",
            ["Admin.Configuration.Stores.Fields.HolidayName"] = "Nome do feriado",
            ["Admin.Configuration.Stores.Fields.HolidayName.hint"] = "Título do feriado",
            ["Admin.Configuration.Stores.Fields.LargeOrderEmailAddress"] = "Endereço de e-mail",
            ["Admin.Configuration.Stores.Fields.LargeOrderOrderAmount"] = "Valor do pedido",
            ["Admin.Configuration.Stores.Fields.Monday"] = "Segunda-feira",
            ["Admin.Configuration.Stores.Fields.Monday.hint"] = "Segunda-feira",
            ["Admin.Configuration.Stores.Fields.PreOrderEmailAddress"] = "Endereço de e-mail",
            ["Admin.Configuration.Stores.Fields.PreOrderNotificationTime"] = "Hora da notificação",
            ["Admin.Configuration.Stores.Fields.Saturday"] = "Sábado",
            ["Admin.Configuration.Stores.Fields.Saturday.hint"] = "Sábado",
            ["Admin.Configuration.Stores.Fields.StartTime"] = "Hora de início",
            ["Admin.Configuration.Stores.Fields.StartTime.hint"] = "Hora de início",
            ["Admin.Configuration.Stores.Fields.StoreCode"] = "Código da loja",
            ["Admin.Configuration.Stores.Fields.StoreCode.Hint"] =
                "Código de loja exclusivo (opcional) para usar em relatórios de vendas",
            ["Admin.Configuration.Stores.Fields.StorePickUp"] = "Retirada na loja",
            ["Admin.Configuration.Stores.Fields.Sunday"] = "Domingo",
            ["Admin.Configuration.Stores.Fields.Sunday.hint"] = "Domingo",
            ["Admin.Configuration.Stores.Fields.Thursday"] = "Quinta-feira",
            ["Admin.Configuration.Stores.Fields.Thursday.hint"] = "Quinta-feira",
            ["Admin.Configuration.Stores.Fields.Tuesday"] = "Terça-feira",
            ["Admin.Configuration.Stores.Fields.Tuesday.hint"] = "Terça-feira",
            ["Admin.Configuration.Stores.Fields.UniqueId"] = "ID exclusivo",
            ["Admin.Configuration.Stores.Fields.Wednesday"] = "Quarta-feira",
            ["Admin.Configuration.Stores.Fields.Wednesday.hint"] = "Quarta-feira",
            ["Admin.Configuration.Stores.ImportFromCsv"] = "Importar lojas de CSV",
            ["Admin.Configuration.Stores.OverlappingTimingConfigurations"] =
                "As alterações de configuração solicitadas se sobrepõem aos horários atuais da loja para o dia selecionado. Corrija e tente novamente.",
            ["Admin.Configuration.Stores.ReasonLabel"] = "Selecione um motivo:",
            ["Admin.Configuration.Tax"] = "Imposto",
            ["Admin.Configuration.Tax.Mapping.Fields.AddNew"] = "Adicionar novo mapeamento",
            ["Admin.Configuration.Tax.Mapping.Fields.OrderType"] = "Tipo de pedido",
            ["Admin.Configuration.Tax.Mapping.Fields.Store"] = "Loja",
            ["Admin.Configuration.Tax.Mapping.Fields.Store.All"] = "Todas as lojas",
            ["Admin.Configuration.Tax.Mapping.Fields.TaxCategories.All"] = "Todas as categorias de impostos",
            ["Admin.Configuration.Tax.Mapping.Fields.TaxCategory"] = "Categoria de imposto",
            ["Admin.Configuration.Tax.TaxStoreOrderTypeMapping"] = "Mapeamentos fiscais",
            ["Admin.Language.RunMigrations"] = "Executar migrações",
            ["Admin.Language.RunMigrations.Failure"] = "Não foi possível executar as migrações, mensagem de erro: ",
            ["Admin.Language.RunMigrations.Success"] = "Migrações executadas com sucesso.",
            ["Admin.Orders.Fields.OrderType"] = "Tipo de pedido",
            ["Admin.Promotions.Discounts.Fields.CouponCode.Required"] = "Forneça um código de cupom",
            ["Admin.Reports.StoreStatus"] = "Status da loja",
            ["Admin.Reports.StoreStatus.EndDate"] = "Data final",
            ["Admin.Reports.StoreStatus.Fields.Comment"] = "Comentário",
            ["Admin.Reports.StoreStatus.Fields.Date"] = "Data",
            ["Admin.Reports.StoreStatus.Fields.Reason"] = "Motivo",
            ["Admin.Reports.StoreStatus.Fields.Status"] = "Status da loja",
            ["Admin.Reports.StoreStatus.Fields.StoreId"] = "ID da loja",
            ["Admin.Reports.StoreStatus.Fields.StoreName"] = "Nome da loja",
            ["Admin.Reports.StoreStatus.RunReport"] = "Executar relatório",
            ["Admin.Reports.StoreStatus.StartDate"] = "Data de início",
            ["Admin.Reports.StoreStatus.Status"] = "Status da loja",
            ["Admin.Reports.StoreStatus.Store"] = "Loja",
            ["Admin.Stores.Stores.List.SearchName"] = "Nome da loja",
            ["Admin.Stores.Stores.List.SearchStoreStatus"] = "Status",
            ["Admin.Stores.Stores.List.SearchUniqueId"] = "ID exclusivo",
            ["Archies.Header.About"] = "Sobre",
            ["Archies.Header.ArchiesFoundation"] = "A Fundação Archie ",
            ["Archies.Header.Jobs"] = "Carreiras",
            ["Archies.Header.Menu"] = "Menu",
            ["Archies.Header.News"] = "Notícias",
            ["Archies.Login"] = "Login",
            ["Archies.Logout"] = "Sair",
            ["BridgeTerm.carbohydratesGrams.Title"] = "Carboidratos",
            ["BridgeTerm.carbohydratesGrams.Unit"] = " g",
            ["BridgeTerm.carbohydratesGrams.Unit"] = "g",
            ["BridgeTerm.chlorineMilligrams.Title"] = "Cloro",
            ["BridgeTerm.chlorineMilligrams.Unit"] = " mg",
            ["BridgeTerm.chlorineMilligrams.Unit"] = "mg",
            ["BridgeTerm.energyKcal.Title"] = "Energia",
            ["BridgeTerm.energyKcal.Unit"] = "kCal",
            ["BridgeTerm.fatGrams.Title"] = "Gordo",
            ["BridgeTerm.fatGrams.Unit"] = " g",
            ["BridgeTerm.fatGrams.Unit"] = "g",
            ["BridgeTerm.healthRating.Title"] = "Classificação de Saúde",
            ["BridgeTerm.healthRating.Unit"] = " ",
            ["BridgeTerm.hydrogenCarbonateMilligrams.Title"] = "Hidrogênio Carbonato",
            ["BridgeTerm.hydrogenCarbonateMilligrams.Unit"] = "mg",
            ["BridgeTerm.magnesiumMilligrams.Title"] = "Magnésio",
            ["BridgeTerm.magnesiumMilligrams.Unit"] = " mg",
            ["BridgeTerm.magnesiumMilligrams.Unit"] = "mg",
            ["BridgeTerm.nitratesMilligrams.Title"] = "Nitratos",
            ["BridgeTerm.nitratesMilligrams.Unit"] = "mg",
            ["BridgeTerm.phValue.Title"] = "Valor PH",
            ["BridgeTerm.phValue.Unit"] = " ",
            ["BridgeTerm.potassiumMilligrams.Title"] = "Potássio",
            ["BridgeTerm.potassiumMilligrams.Unit"] = " mg",
            ["BridgeTerm.potassiumMilligrams.Unit"] = "mg",
            ["BridgeTerm.proteinGrams.Title"] = "Proteína",
            ["BridgeTerm.proteinGrams.Unit"] = " g",
            ["BridgeTerm.saltGrams.Title"] = "Sal",
            ["BridgeTerm.saltGrams.Unit"] = " g",
            ["BridgeTerm.saturatedFatGrams.Title"] = "Gordura Saturada",
            ["BridgeTerm.saturatedFatGrams.Unit"] = " g",
            ["BridgeTerm.sodiumMilligrams.Title"] = "Sódio",
            ["BridgeTerm.sodiumMilligrams.Unit"] = " mg",
            ["BridgeTerm.sodiumGrams.Title"] = "Sódio",
            ["BridgeTerm.sodiumGrams.Unit"] = " g",
            ["BridgeTerm.sugarGrams.Title"] = "Açúcar",
            ["BridgeTerm.sugarGrams.Unit"] = " g",
            ["BridgeTerm.sulfatesMilligrams.Title"] = "Sulfatos",
            ["BridgeTerm.sulfatesMilligrams.Unit"] = " mg",
            ["BridgeTerm.fibreGrams.Title"] = "Fibra",
            ["BridgeTerm.fibreGrams.Unit"] = " g",
            ["Checkorder.ProblematicMappings.Error"] = "Há um problema com os itens em seu carrinho.",
            ["Checkout.BackToMenu"] = "Voltar ao menu",
            ["Checkout.CouldNotPlaceOrder"] = "Não foi possível fazer seu pedido",
            ["Checkout.CustomerCheckout"] = "Checkout do cliente",
            ["Checkout.CustomerCheckout.ReviewYourOrder"] = "Revisar seu pedido",
            ["Checkout.CustomerInformation.Curbside.Details"] = "Seus detalhes",
            ["Checkout.CustomerInformation.Curbside.Vehicle"] = "Detalhes do seu veículo",
            ["Checkout.CustomerInformation.Vehicle.Colour"] = "Cor",
            ["Checkout.CustomerInformation.Vehicle.Model"] = "Modelo / Marca",
            ["Checkout.CustomerInformation.Vehicle.Plate"] = "Placa de Matrícula",
            ["Checkout.CustomertInformation.Address1"] = "Endereço 1",
            ["Checkout.CustomertInformation.Address2"] = "Endereço 2",
            ["Checkout.CustomertInformation.City"] = "Cidade",
            ["Checkout.CustomertInformation.Country"] = "Selecionar país",
            ["Checkout.CustomertInformation.County"] = "Condado",
            ["Checkout.CustomertInformation.DeliveryInstructions"] = "Instruções de entrega",
            ["Checkout.CustomertInformation.Email"] = "E-mail",
            ["Checkout.CustomertInformation.FaxNumber"] = "Fax",
            ["Checkout.CustomertInformation.FirstName"] = "Nome",
            ["Checkout.CustomertInformation.Igreetothe"] = "Concordo com o",
            ["Checkout.CustomertInformation.LastName"] = "Sobrenome",
            ["Checkout.CustomertInformation.OrderNotes"] = "Notas do pedido",
            ["Checkout.CustomertInformation.PhoneNumber"] = "Telefone",
            ["Checkout.CustomertInformation.SaveAddress"] = "Salvar este endereço em minha lista de endereços",
            ["Checkout.CustomertInformation.SaveVehicle"] = "Salvar este veículo em minha lista de veículos",
            ["Checkout.CustomertInformation.StateProvince"] = "Selecionar Estado",
            ["Checkout.CustomertInformation.TermsAndCondition"] = "Termos e condições",
            ["Checkout.CustomertInformation.ZipPostalCode"] = "PostCode",
            ["Checkout.EnterCVV.Wait"] = "Insira o CV2 para este cartão",
            ["Checkout.GroupOrdering.Group"] = "Pedido de grupo",
            ["Checkout.GuestCheckout"] = "Check-out do visitante",
            ["Checkout.GuestCheckout.ReviewYourOrder"] = "Revisar seu pedido",
            ["Checkout.Interested.Title"] = "Com base em sua seleção, você pode estar interessado nos seguintes itens",
            ["Checkout.MarketingEmails"] = "Receba nossos e-mails de marketing e ofertas",
            ["Checkout.MarketingEmailsOptOut"] = "Não receba nossos e-mails de marketing e ofertas",
            ["Checkout.Oops.Button.BackToMenu"] = "VOLTAR AO MENU",
            ["Checkout.Oops.Button.TryAgain"] = "TENTE NOVAMENTE",
            ["Checkout.Oops.ItemsHaveBeenSave"] = "Não se preocupe, seus itens foram salvos.",
            ["Checkout.Oops.Title"] = "Ops!",
            ["Checkout.Oops.UnableToProcess"] =
                "Infelizmente não foi possível processar seu pagamento. Verifique se você tem fundos suficientes ou tente outro cartão.",
            ["Checkout.Order"] = "Pedido",
            ["Checkout.OrderDetails.Button.Finish"] = "Concluir",
            ["Checkout.OrderDetails.Button.SaveReceipt"] = "SALVAR RECIBO",
            ["Checkout.OrderDetails.Button.StartNewOrder"] = "INICIAR UM NOVO PEDIDO",
            ["Checkout.OrderDetails.Collection.Address"] = "Endereço da coleta",
            ["Checkout.OrderDetails.Collection.Time"] = "Hora da coleta",
            ["Checkout.OrderDetails.Curbside.Address"] = "Endereço de coleta",
            ["Checkout.OrderDetails.Curbside.Time"] = "Hora da coleta",
            ["Checkout.OrderDetails.Delivery.Address"] = "Endereço de entrega",
            ["Checkout.OrderDetails.DineIn.WeRecommendYouArrive"] =
                "Nosso objetivo é levar seu pedido à sua mesa em dez minutos",
            ["Checkout.OrderDetails.Title"] = "Boas notícias!",
            ["Checkout.OrderDetails.Title.FiveguysES"] = "Obrigado",
            ["Checkout.OrderDetails.Title.FiveguysUK"] = "Obrigado",
            ["Checkout.OrderDetails.Title.FiveguysDE"] = "Obrigado",
            ["Checkout.OrderDetails.Title.chikn"] = "Obrigado",
            ["Checkout.OrderDetails.WeRecommendYouArrive"] =
                "Recomendamos que você chegue no máximo 5 minutos antes ou depois de 5 minutos para coletar seu pedido, isso garantirá que sua comida seja preparada na hora na hora da coleta.",
            ["Checkout.OrderDetails.YourOrderHasBeenAccepted"] =
                "Seu pedido foi aceito e você receberá um e-mail de confirmação em breve.",
            ["Checkout.OrderSummary.Change"] = "Alterar",
            ["Checkout.OrderSummary.Title"] = "Resumo do pedido",
            ["Checkout.OrderSummary.Total"] = "Total",
            ["Checkout.PaymentButton.ProceedToPaymentOptions"] = "PROSSEGUIR PARA AS OPÇÕES DE PAGAMENTO",
            ["Checkout.PaymentButton.ProceedToPaymentOptions.FiveguysES"] = "CONTINUAR PARA O PAGAMENTO",
            ["Checkout.PaymentButton.ProceedToPaymentOptions.FiveguysUK"] = "PROSSEGUIR PARA O PAGAMENTO",
            ["Checkout.PaymentButton.ProceedToPaymentOptions.FiveguysDE"] = "PROSSEGUIR PARA O PAGAMENTO",
            ["Checkout.PaymentInfo.Button"] = "CONTINUAR COM O PAGAMENTO",
            ["Checkout.PaymentMethod.BacktoMenu"] = "Voltar",
            ["Checkout.PaymentMethod.Button.DigitalWallet"] = "Carteira digital",
            ["Checkout.PaymentMethod.Button.PayUsingDigitalWallet"] = "Pagar com carteira digital",
            ["Checkout.PaymentMethod.Button.PayWithCard"] = "Pagar com cartão",
            ["Checkout.PaymentMethod.Popup.PayWithDigital"] = "Pagar com carteira digital",
            ["Checkout.PaymentMethod.Popup.Title"] = "Como você gostaria de pagar?",
            ["Checkout.PaymentMethod.Popup.Title.PaymentMethod"] = "MÉTODO DE PAGAMENTO",
            ["Checkout.PaymentMethod.WalletDisclaimer"] =
                "* O Apple Pay está disponível apenas no Safari. O Google Pay está disponível apenas no Chrome",
            ["Checkout.Please.Wait"] = "Processando sua solicitação, aguarde...",
            ["Checkout.PrivacyPolicy"] = "política de privacidade",
            ["Checkout.PrivacyPolicy.Note"] =
                "Usamos as informações que você nos fornece aqui para processar seu pedido. Para saber mais informações sobre como e por que usamos as informações, consulte nossa política de privacidade",
            ["Checkout.PrivacyPolicy.Note.Partial"] =
                "Usamos as informações que você nos fornece aqui para processar seu pedido. Para saber mais informações sobre como e por que usamos as informações, consulte nosso ",
            ["Checkout.ProcessingOrder.message"] = "Processando pedido",
            ["Checkout.ProcessingOrder.message.FiveguysES"] = "PROCESSANDO PAGAMENTO...",
            ["Checkout.ProcessingOrder.message.FiveguysUK"] = "PROCESSANDO PAGAMENTO...",
            ["Checkout.ProcessingOrder.message.FiveguysDE"] = "PROCESSANDO PAGAMENTO...",
            ["Checkout.Recaptcha.Error"] = "Recaptcha precisa ser concluído primeiro.",
            ["Checkout.RemoveAllItem.ClearOrder"] = "LIMPAR PEDIDO",
            ["Checkout.RemoveAllItem.Confirmation.Continue"] = "CONTINUAR",
            ["Checkout.RemoveAllItem.Confirmation.Continue.FiveguysES"] = "SIM",
            ["Checkout.RemoveAllItem.Confirmation.Continue.FiveguysUK"] = "SIM",
            ["Checkout.RemoveAllItem.Confirmation.Continue.FiveguysDE"] = "SIM",
            ["Checkout.RemoveAllItem.Confirmation.GoBack"] = "VOLTAR",
            ["Checkout.RemoveAllItem.Confirmation.GoBack.FiveguysES"] = "NÃO",
            ["Checkout.RemoveAllItem.Confirmation.GoBack.FiveguysUK"] = "NÃO",
            ["Checkout.RemoveAllItem.Confirmation.GoBack.FiveguysDE"] = "NÃO",
            ["Checkout.RemoveAllItem.Confirmation.Message"] = "Isso removerá todos os itens de seu pedido",
            ["Checkout.RemoveAllItem.Confirmation.Message.FiveguysES"] = "Remover todos os itens do seu pedido?",
            ["Checkout.RemoveAllItem.Confirmation.Message.FiveguysUK"] = "Remover todos os itens do seu pedido?",
            ["Checkout.RemoveAllItem.Confirmation.Message.FiveguysDE"] = "Remover todos os itens do seu pedido?",
            ["Checkout.RemoveItem.Confirmation.Message"] = "Tem certeza de que deseja remover este item?",
            ["Checkout.RemoveItem.Confirmation.No"] = "Não",
            ["Checkout.RemoveItem.Confirmation.Yes"] = "Sim",
            ["Checkout.SomethingWentWrong"] = "Algo deu errado ao tentar processar seu pedido.",
            ["Checkout.Subtitle"] = "Digite seus dados abaixo, ou",
            ["Checkout.SubtitleShort"] = "Digite seus dados abaixo",
            ["Checkout.Subtitle.LoginRegister"] = "login / registrar",
            ["Chikn.Footer.Registered"] = "&copy; Frango 2022 Registrado",
            ["Common.AddAddress"] = "Adicionar endereço",
            ["Common.AddVehicle"] = "Adicionar veículo",
            ["Common.EditAddress"] = "Editar endereço",
            ["Common.EditVehicle"] = "Editar veículo",
            ["Common.Product.BackToMenu"] = "Voltar ao Menu",
            ["Common.Product.BackToMenu.FiveguysES"] = "Voltar",
            ["Common.Product.BackToMenu.FiveguysUK"] = "Voltar",
            ["Common.Product.BackToMenu.FiveguysDE"] = "Voltar",
            ["Curbside.Vehicle"] = "VEÍCULO",
            ["Curbside.Vehicle.PlateIsRequired"] = "É necessária a placa de matrícula.",
            ["Curbside.Vehicle.VehicleModelIsRequired"] = "O modelo do veículo é obrigatório.",
            ["Curbside.maintitle"] = "Quando você gostaria de ",
            ["Curbside.note"] =
                "Observação: você será solicitado a estacionar em uma área designada. Os horários podem mudar durante o processo de pedido, o horário real será confirmado durante a finalização da compra.",
            ["Curbside.searchtitle"] = "Retirada na calçada de",
            ["Curbside.subtitle"] = "retirar seu pedido?",
            ["Curbside.updatemaintitle"] = "POR FAVOR, SELECIONE UM NOVO",
            ["Curbside.updatesearchtitle"] =
                "Seu horário anterior não está mais disponível <br/> seu carrinho permanece salvo",
            ["Curbside.updatesubtitle"] = "HORÁRIO DE RETIRADA NA CURBSIDE",
            ["Default.Continue"] = "Continuar",
            ["Default.Default"] = "Padrão",
            ["Default.Ok"] = "OK",
            ["Delivery.maintitle"] = "QUANDO VOCÊ GOSTARIA DO SEU",
            ["Delivery.note"] =
                "Observação: o tempo de entrega disponível pode mudar durante o processo de pedido, o horário de entrega real será confirmado durante a finalização da compra.",
            ["Delivery.searchtitle"] = "Entrega de",
            ["Delivery.subtitle"] = "PEDIDO ENTREGUE?",
            ["Delivery.updatemaintitle"] = "POR FAVOR, SELECIONE UM NOVO",
            ["Delivery.updatesearchtitle"] =
                "Seu horário anterior não está mais disponível <br/> seu carrinho permanece salvo",
            ["Delivery.updatesubtitle"] = "HORA DE ENTREGA",
            ["DineIn.Subtitle.Unavailable"] = "Lamentamos, mas o jantar não está disponível para esta loja",
            ["DineIn.TableAt"] = " à mesa ",
            ["DineIn.Title"] = "Jantar em",
            ["DineIn.placeholder.tablenumber"] = "Digite o número da sua mesa",
            ["DineIn.startorder"] = "Iniciar pedido",
            ["DineIn.subtitle"] = "Serviço de mesa em:",
            ["FINDPOSTCODE.YOUHAVEPREVIOUSORDERS.FIVEGUYS"] = "Você tem pedidos anteriores",
            ["FiveGuys.Footer.AllergenInfo"] = "Informações do alérgeno",
            ["FiveGuys.Footer.Contact"] = "Contato",
            ["FiveGuys.Footer.FAQs"] = "FAQs",
            ["FiveGuys.Footer.Ingredients"] = "Ingredientes",
            ["FiveGuys.Footer.Legal"] = "Legal",
            ["FiveGuys.Footer.NutritionalInfo"] = "Informações Nutricionais",
            ["FiveGuys.Footer.PrivacyPolicy"] = "Política de Privacidade",
            ["FiveGuys.Footer.TermsConditions"] = "Termos e condições",
            ["FiveGuys.Header.AboutUs"] = "Sobre nós",
            ["FiveGuys.Header.GiftCards"] = "Cartões-presente",
            ["FiveGuys.Header.Jobs"] = "Trabalhos",
            ["FiveGuys.Header.Location"] = "Local",
            ["FiveGuys.Header.Menu"] = "Menu",
            ["FiveGuys.Header.Merch"] = "Mercado",
            ["Footer.PoweredByLineten"] = "Desenvolvido por Lineten",
            ["GroupOrdering.Cancel"] = "Cancelar",
            ["GroupOrdering.CompleteMyOrder"] = "Concluir meu pedido",
            ["GroupOrdering.ContinueToCheckout"] = "Continuar para finalizar a compra",
            ["GroupOrdering.CreateGroup"] = "Criar Grupo",
            ["GroupOrdering.CreateGroup.InviteYourGuests"] = "Convide seus convidados compartilhando o link abaixo",
            ["GroupOrdering.CreateGroup.ProceedToMenu"] = "Ir para o menu",
            ["GroupOrdering.CreateGroup.Share"] = "Compartilhar",
            ["GroupOrdering.CreateGroup.Success"] = "Seu pedido de grupo foi criado",
            ["GroupOrdering.CreateGroupOrder"] = "Criar pedido de grupo",
            ["GroupOrdering.CreateGroupOrder.Mobile"] = "Pedido de grupo",
            ["GroupOrdering.CreateGroupOrder.Subtitle"] =
                "Crie seu grupo e convide convidados para adicionar seus pedidos à cesta!",
            ["GroupOrdering.DeleteGroupOrder"] = "Cancelar pedido de grupo",
            ["GroupOrdering.Finish"] = "Concluir",
            ["GroupOrdering.Finished"] = "Concluído",
            ["GroupOrdering.GoBack"] = "Voltar",
            ["GroupOrdering.GroupName"] = "Nomeie seu Grupo",
            ["GroupOrdering.GroupNameError"] = "O nome do grupo é obrigatório",
            ["GroupOrdering.Guests"] = "Convidados",
            ["GroupOrdering.Invitation"] = "Olá, você foi convidado a participar de um pedido em grupo",
            ["GroupOrdering.IsEveryoneReady"] = "Todos estão prontos?",
            ["GroupOrdering.IsEveryoneReady.Subtitle"] =
                "Parece que um ou mais convidados não terminaram. <br/><br/> Se você finalizar a compra, o pedido em grupo será bloqueado para seus convidados e eles não ser capaz de editar seus itens.",
            ["GroupOrdering.Item"] = "item",
            ["GroupOrdering.Items"] = "itens",
            ["GroupOrdering.ItemsAdded"] = "Seus itens foram adicionados ao pedido final do grupo",
            ["GroupOrdering.JoinGroup.Details"] = "Você pode adicionar itens a este pedido e tudo será coletado junto.",
            ["GroupOrdering.JoinGroup.EnterYourName"] = "Digite seu nome e entre no grupo",
            ["GroupOrdering.JoinGroup.HostIsPaying"] = ":: O host está pagando por este pedido ::",
            ["GroupOrdering.JoinGroup.Join"] = "Participar",
            ["GroupOrdering.JoinGroup.JoinOrder"] = "Pedido de associação",
            ["GroupOrdering.JoinGroup.Order"] = "pedido?",
            ["GroupOrdering.KeepGuest"] = "Manter convidado",
            ["GroupOrdering.LeaveGroup"] = "Sair do grupo?",
            ["GroupOrdering.LeaveGroup.Subtitle"] = "Você e seus itens serão removidos do grupo.",
            ["GroupOrdering.LeaveGroupOrder"] = "Sair do grupo",
            ["GroupOrdering.Owner"] = "Proprietário",
            ["GroupOrdering.ReadyToFinish"] = "Pronto para terminar?",
            ["GroupOrdering.ReadyToFinish.Subtitle"] =
                "Se continuar, você não poderá mais editar seus itens e terá que entrar em contato com o proprietário do grupo para fazer alterações.",
            ["GroupOrdering.RemoveGuest"] = "Remover convidado",
            ["GroupOrdering.RemoveGuest.AreYouSure"] = "Remover convidado do Pedido de Grupo?",
            ["GroupOrdering.RemoveGuest.Subtitle"] =
                "Este Convidado e todos os itens que ele adicionou serão removidos do seu pedido de grupo.",
            ["GroupOrdering.StayInGroup"] = "Permanecer no grupo",
            ["GroupOrdering.SubTotal"] = " Subtotal: ",
            ["GroupOrdering.Timeslot.Notes"] =
                "Observação: os horários podem mudar um pouco durante o processo de pedido. Seu horário de coleta será confirmado durante a finalização da compra.",
            ["GroupOrdering.Timeslot.Unavailable"] =
                "Para nos ajudar a preparar seu pedido de grupo, ajustamos seu horário de coleta.",
            ["GroupOrdering.You"] = "Você",
            ["GroupOrdering.YouHaveLeft"] = "Você saiu da ordem do grupo",
            ["JourneyRestart.SessionExpired"] = "Sua sessão expirou",
            ["KitchenCapacity.SelectSlots"] = "Selecionar espaço",
            ["Menu.OnlineOrder"] = "Pedido",
            ["Menu.Ordersummary.Checkout"] = "CHECKOUT",
            ["Menu.Ordersummary.ClearAll"] = "LIMPAR PEDIDO",
            ["Menu.Ordersummary.Collection.Change"] = "Alterar",
            ["Menu.Ordersummary.Collection.Collection"] = "Coletar de",
            ["Menu.Ordersummary.Collection.Curbside"] = "Retirada na calçada",
            ["Menu.Ordersummary.Collection.Delivery"] = "Entrega de",
            ["Menu.Ordersummary.Collection.DineIn"] = "Jantar em",
            ["Menu.Ordersummary.Collection.TimeAt"] = "em",
            ["Menu.Ordersummary.Collection.TimeFrom"] = "de",
            ["Menu.Ordersummary.Collection.TimeTo"] = "para",
            ["Menu.Ordersummary.EmptyOrder"] =
                "Seu pedido está vazio, clique em um item para adicioná-lo ao seu pedido.",
            ["Menu.Ordersummary.GroupOrder.Mobile.Checkout"] = "Revisar meus itens",
            ["Menu.Ordersummary.GroupOrder.OrderTotal"] = "Total do pedido do grupo: ",
            ["Menu.Ordersummary.InvertedCheckbox.Prefix"] = "NÃO",
            ["Menu.Ordersummary.Modalpopup.ClearAllItem.Back"] = "VOLTAR",
            ["Menu.Ordersummary.Modalpopup.ClearAllItem.Continue"] = "CONTINUAR",
            ["Menu.Ordersummary.Modalpopup.ClearAllItem.Text"] = "Isso removerá todos os itens<br/>de seu pedido",
            ["Menu.Ordersummary.Modalpopup.ClearAllItem.Text.FiveguysES"] =
                "Isso removerá<br/>todos os itens<br/>de seu pedido",
            ["Menu.Ordersummary.Modalpopup.ClearAllItem.Text.FiveguysUK"] =
                "Isso removerá<br/>todos os itens<br/>do seu pedido",
            ["Menu.Ordersummary.Modalpopup.ClearAllItem.Text.FiveguysDE"] =
                "Isso removerá<br/>todos os itens<br/>do seu pedido",
            ["Menu.Ordersummary.Modalpopup.RemoveItem.No"] = "Não",
            ["Menu.Ordersummary.Modalpopup.RemoveItem.Text1"] = "Tem certeza que deseja",
            ["Menu.Ordersummary.Modalpopup.RemoveItem.Text2"] = "remover este item?",
            ["Menu.Ordersummary.Modalpopup.RemoveItem.Yes"] = "Sim",
            ["Menu.Ordersummary.ReviewOrder"] = "REVISAR PEDIDO",
            ["Menu.Ordersummary.ReviewOrder.FiveguysES"] = "VER PEDIDO",
            ["Menu.Ordersummary.ReviewOrder.FiveguysUK"] = "VER PEDIDO",
            ["Menu.Ordersummary.ReviewOrder.FiveguysDE"] = "VER PEDIDO",
            ["Menu.Ordersummary.ReviewYourOrder"] = "REVISE SEU PEDIDO",
            ["Menu.Ordersummary.Title"] = "Resumo do pedido",
            ["Menu.Ordersummary.Total"] = "Total",
            ["Menu.Ordersummary.back"] = "Voltar",
            ["Menu.AllergensModal.Title"] = "Uma nota para nossos hóspedes com alergias",
            ["Menu.AllergensModal.SubTitle"] =
                "Infelizmente, não podemos aceitar pedidos de alergia on-line ou por telefone",
            ["Menu.AllergensModal.FirstParagraph"] =
                "Esta decisão garante a segurança dos nossos hóspedes com alergias, caso pretenda fazer uma encomenda para alergias, pedimos-lhe que se dirija a um dos nossos restaurantes + faça a sua encomenda com um membro da equipa.",
            ["Menu.AllergensModal.SecondParagraph"] =
                "Esta decisão visa garantir a segurança dos nossos hóspedes com alergias. Se você deseja fazer um pedido com uma modificação de alergia, pedimos que visite um de nossos restaurantes e faça seu pedido a um membro da equipe.",
            ["Menu.AllergensModal.ContinueButton"] = "Continuar pedido",
            ["Menu.AllergensModal.ViewGuidelinesButton"] = "Ver diretrizes",
            ["Order.Allergies.Notes.FiveguysES"] =
                "Lamentamos, mas não podemos atender alergias ou intolerâncias alimentares feitas on-line, apenas pedidos na loja. Por motivos de saúde e segurança, se você sofre de alergia a amendoim, faça não peça um milk-shake de batatas fritas. Se precisar de qualquer informação sobre alérgenos em alimentos, consulte os guias de alérgenos e ingredientes nos links abaixo.",
            ["Order.Allergies.Notes.FiveguysUK"] =
                "Lamentamos, mas não podemos atender a alergias ou intolerâncias alimentares feitas on-line, apenas pedidos na loja. Por motivos de saúde e segurança, se você sofre de alergia a amendoim, faça não peça um milk-shake de batatas fritas. Se precisar de qualquer informação sobre alérgenos em alimentos, consulte os guias de alérgenos e ingredientes nos links abaixo.",
            ["Order.Allergies.Notes.FiveguysDE"] =
                "Lamentamos, mas não podemos atender a alergias ou intolerâncias alimentares feitas on-line, apenas pedidos na loja. Por motivos de saúde e segurança, se você sofre de alergia a amendoim, faça não peça um milk-shake de batatas fritas. Se precisar de qualquer informação sobre alérgenos em alimentos, consulte os guias de alérgenos e ingredientes nos links abaixo.",
            ["Order.Maximumorder"] = "Pedido máximo",
            ["Order.Minimumorder"] = "Pedido mínimo",
            ["Order.OrderAgain"] = "Pedir novamente",
            ["Order.OrderConfirmation.AddressTextCollection"] = "Endereço da coleção: ",
            ["Order.OrderConfirmation.AddressTextDelivery"] = "Endereço de entrega: ",
            ["Order.OrderDetails"] = "DETALHES DO PEDIDO",
            ["Order.OrderTotal"] = "Total",
            ["Order.Type.Notes.FiveguysES"] =
                "<p><strong>Curbside:</strong> Para pedidos na calçada, você será solicitado a estacionar em uma área designada. Consulte a confirmação do pedido para obter detalhes. </ p> <p><strong>Coletar+:</strong> Preparamos quando você estiver por perto</p>",
            ["Order.Type.Notes.FiveguysUK"] =
                "<p><strong>Curbside:</strong> Para pedidos na calçada, você será solicitado a estacionar em uma área designada. Consulte a confirmação do pedido para obter detalhes. </ p> <p><strong>Coletar+:</strong> Preparamos quando você estiver por perto</p>",
            ["Order.Type.Notes.FiveguysDE"] =
                "<p><strong>Curbside:</strong> Para pedidos na calçada, você será solicitado a estacionar em uma área designada. Consulte a confirmação do pedido para obter detalhes. </ p> <p><strong>Coletar+:</strong> Preparamos quando você estiver por perto</p>",
            ["POSBridge.SubmitFail.PlaceOrder.RefundFailed"] =
                "Infelizmente, devido a problemas técnicos, a loja não pode recebê-lo. <br/> Não foi possível reembolsar seu pedido, entre em contato conosco.",
            ["POSBridge.SubmitFail.PlaceOrder.RefundSucceed"] =
                "Infelizmente, devido a problemas técnicos, a loja não pode recebê-lo. <br/> Seu pedido foi reembolsado com sucesso.",
            ["PageTitle.GroupOrdering.JoinGroup"] = "Entrar no pedido do grupo",
            ["Payment.ProcessingOrder.Timeout"] =
                "Seu pagamento foi bem-sucedido, mas não foi possível confirmar o pedido com a loja, entre em contato diretamente com a loja para verificar se é necessário um reembolso: ",
            ["PaymentMethod.OngoingOrder.Back"] = "Você não concluiu seu pagamento com sucesso",
            ["Product.AllergensAndIngredients"] = "Alergênicos e informações nutricionais",
            ["Product.AllergensAndIngredients.Allergens.Subtitle"] = "O produto contém os seguintes alérgenos",
            ["Product.AllergensAndIngredients.ModalAllergensTab"] = "Alérgenos",
            ["Product.AllergensAndIngredients.ModalIngredientsTab"] = "Ingredientes",
            ["Product.AllergensAndIngredients.ModalNutritionTab"] = "Nutrição",
            ["Product.AllergensAndIngredients.ModalTitle"] = "Informações sobre nutrição e alérgenos",
            ["Product.AllergensAndIngredients.ModalTitle.FiveguysES"] = "Nutrição e Alergênicos",
            ["Product.AllergensAndIngredients.ModalTitle.FiveguysUK"] = "Nutrição e Alergênicos",
            ["Product.AllergensAndIngredients.ModalTitle.FiveguysDE"] = "Nutrição e Alergênicos",
            ["Product.AllergensAndIngredients.Nutrition.SubtitleLeft"] = "Valores típicos",
            ["Product.AllergensAndIngredients.Nutrition.SubtitleRight"] = "Por 100g",
            ["Product.Attributes.Max.Selection.Not.Met"] = "Muitos valores de atributos selecionados",
            ["Product.Attributes.Min.Selection.Not.Met"] = "Poucos valores de atributos selecionados",
            ["Products.LimitedTimeAvailability.Product"] = "Disponibilidade por tempo limitado*",
            ["Products.LimitedTimeAvailability.Product.OutOfStock"] = "Fora de estoque",
            ["Products.RelatedProductsNxg"] = "Você também pode gostar...",
            ["Products.ProductInfo"] = "Informação do produto",
            ["Punchh.SeeYourRewards"] = "Veja suas recompensas",
            ["ReOrder.Error.ReservationNotFound"] =
                "Não foi possível escolher a loja para este pedido, mas os itens foram adicionados ao seu carrinho, use o botão 'Tentar novamente' para escolher a loja e continuar com este pedido.",
            ["Reviews.Overview.LoginToReview"] = "Faça login para avaliar este produto",
            ["Reviews.Write.CustomNXG"] = "Revisar para",
            ["Settings.UserJourneySettings.Edit"] = "As configurações da jornada do usuário foram editadas.",
            ["ShoppingCart.AddToCart.Cancel"] = "Cancelar",
            ["ShoppingCart.AddToCart.FiveguysES"] = "Adicionar para ",
            ["ShoppingCart.AddToCart.FiveguysUK"] = "Adicionar para ",
            ["ShoppingCart.AddToCart.FiveguysDE"] = "Adicionar para ",
            ["ShoppingCart.AlterQuantity.FiveguysES"] = "Deseja mais de 1?",
            ["ShoppingCart.AlterQuantity.FiveguysUK"] = "Deseja mais de 1?",
            ["ShoppingCart.AlterQuantity.FiveguysDE"] = "Deseja mais de 1?",
            ["ShoppingCart.CrossSells.FiveguysES"] =
                "Achamos que você também poderia estar interessado nos seguintes itens:",
            ["ShoppingCart.CrossSells.FiveguysUK"] =
                "Achamos que você também poderia estar interessado nos seguintes itens:",
            ["ShoppingCart.CrossSells.FiveguysDE"] =
                "Achamos que você também poderia estar interessado nos seguintes itens:",
            ["ShoppingCart.HaveADiscountCode"] = "Tem um código de desconto?",
            ["ShoppingCart.Totals.DeliveryFees"] = "Taxa de entrega",
            ["Store.SelectDays"] = "Selecionar dia",
            ["Store.Today"] = "Hoje",
            ["Tacobell.Footer.AboutUs"] = "Sobre nós",
            ["Tacobell.Footer.AllergenInfo"] = "Informações do alérgeno",
            ["Tacobell.Footer.AppTerms"] = "Termos do aplicativo Taco Bell",
            ["Tacobell.Footer.CookiesPolicy"] = "Política de Cookies e Anúncios",
            ["Tacobell.Footer.CustomerServices"] = "Contate o Atendimento ao Cliente",
            ["Tacobell.Footer.LatestNews"] = "Últimas notícias",
            ["Tacobell.Footer.Locations"] = "Locais",
            ["Tacobell.Footer.MailingList"] = "Lista de e-mail",
            ["Tacobell.Footer.Menu"] = "Menu",
            ["Tacobell.Footer.NutritionInformation"] = "Informações Nutricionais",
            ["Tacobell.Footer.PrivacyPolicy"] = "Política de Privacidade",
            ["Tacobell.Footer.Registered"] = "Registrado 2021 Taco Bell",
            ["Tacobell.Footer.ResponsibleDisclosure"] = "Divulgação responsável",
            ["Tacobell.Footer.SiteMap"] = "Mapa do site",
            ["Tacobell.Footer.WebsiteTerms"] = "Termos do site",
            ["Tacobell.Footer.WifiPolicy"] = "Política de Wi-Fi da Taco Bell",
            ["Tacobell.Header.ContactUs"] = "Fale conosco",
            ["Tacobell.Header.Locations"] = "Locais",
            ["Tacobell.Header.Menu"] = "Menu",
            ["Tacobell.Login"] = "Login / Cadastro",
            ["Tacobell.Logout"] = "Sair",
            ["Wagamama.Header.Menu"] = "Menú",
            ["Wagamama.Header.Order"] = "Pedido",
            ["Wagamama.Header.Restaurant"] = "Restaurante",
            ["Wagamama.Header.Restaurants"] = "Restaurantes",
            ["Wagamama.Header.Cook"] = "Cozinhar",
            ["Wagamama.Header.Shop"] = "Comprar",
            ["Wagamama.Header.WagamamaWay"] = "Wagamama way",
            ["Wagamama.Header.Gifting"] = "Oferecer",
            ["UserJourney.NoToppingsModalEnabled.Body"] =
                "Apenas verificando se você definitivamente não deseja coberturas.",
            ["UserJourney.NoToppingsModalEnabled.ButtonAddToppings"] = "Adicionar coberturas",
            ["UserJourney.NoToppingsModalEnabled.ButtonDontAddToppings"] = "Não adicionar coberturas",
            ["UserJourney.NoToppingsModalEnabled.Title"] = "Sem coberturas?",
            ["Vehicle.Colour"] = "Cor*",
            ["Vehicle.RegistrationPlate"] = "Número de matrícula*",
            ["Vehicle.VehicleModel"] = "Modelar e fazer*",
            ["admin.catalog.kitchencapacity.storetimings.backtokitchen"] = "Voltar à capacidade da cozinha",
            ["admin.catalog.kitchencapacity.timings.alert.slotreservation"] =
                "Insira a reserva da loja maior ou igual à capacidade do slot",
            ["admin.catalog.mgs.addnew"] = "Adicionar novo seletor de grupo modificador",
            ["admin.catalog.products.productattributeordertypemapping.hint"] =
                "Especificar para qual tipo de pedido (e opcionalmente armazenar) este atributo de produto está disponível",
            ["admin.catalog.products.productattributes.attributes.editstoretimingsdetails"] =
                "Editar detalhes de horários da loja",
            ["admin.catalog.products.productordertypemapping.savebeforeedit"] =
                "Você precisa salvar o produto antes de adicionar novos mapeamentos de tipo de pedido.",
            ["admin.catalog.store.dayselect.savebeforeedit"] =
                "Você precisa salvar a loja antes de poder adicionar dias para esta página da loja.",
            ["admin.catalog.store.holiday.addnew"] = "Adicionar novo feriado",
            ["admin.catalog.store.holiday.exportcsv"] = "Exportar para CSV",
            ["admin.catalog.store.holiday.importcsv"] = "Importar a partir de CSV",
            ["admin.catalog.store.holiday.ExportAllSeasonalCsv"] =
                "Exportar os horários de funcionamento sazonais para CSV",
            ["admin.catalog.store.holiday.ImportAllSeasonalCsv"] =
                "Importar os horários de funcionamento sazonais de CSV",
            ["admin.catalog.store.holiday.alert.addnew"] = "Forneça o nome e a data do feriado.",
            ["admin.catalog.store.holiday.fields.DateError"] = "Data inválida",
            ["admin.catalog.store.holiday.fields.date"] = "Data",
            ["admin.catalog.store.holiday.fields.starttime"] = "Hora de início",
            ["admin.catalog.store.holiday.fields.endtime"] = "Hora final",
            ["admin.catalog.store.holiday.fields.holidayname"] = "Nome do feriado",
            ["admin.catalog.store.holiday.fields.holidaynameerror"] = "Por favor, escolha um nome de feriado válido",
            ["admin.catalog.store.pickupform.savebeforeedit"] =
                "Você precisa salvar a loja antes de poder adicionar retirada para esta página da loja.",
            ["admin.catalog.store.storeholiday.addbutton"] = "Adicionar feriado",
            ["admin.catalog.store.storeholiday.backtostore"] = "voltar à loja",
            ["admin.catalog.store.storeholiday.editstoreholidaydetails"] = "Editar detalhes do feriado da loja",
            ["admin.catalog.store.storetimings.addbutton"] = "Adicionar horário",
            ["admin.catalog.store.storetimings.backtostore"] = "voltar à loja",
            ["admin.catalog.store.timings.addnew"] = "Adicionar novos horários",
            ["admin.catalog.store.timings.alert.addnew"] = "Todos os campos são obrigatórios.",
            ["admin.catalog.store.timings.fields.StartTimeError"] = "Hora de início inválida",
            ["admin.catalog.store.timings.fields.endtime"] = "Hora final",
            ["admin.catalog.store.timings.fields.starttime"] = "Hora de início",
            ["admin.catalog.store.workday.selectbeforeedit"] = "Selecione primeiro os dias de funcionamento",
            ["admin.common.configure"] = "Configuração da loja",
            ["admin.configuration.Spa.timings.selectday"] = "Selecionar dias",
            ["admin.configuration.catalog.menupublish"] = "Estado da publicação do menu",
            ["Admin.Configuration.MenuPublish.List.SearchMenuPublishStatus"] = "Estado de publicação",
            ["Admin.Configuration.MenuPublish.List.SearchStoreName"] = "Nome da loja",
            ["admin.configuration.menupublish.completedat"] = "Concluído em (UTC)",
            ["admin.configuration.menupublish.details"] = "Detalhes",
            ["admin.configuration.menupublish.receivedat"] = "Recebido em (UTC)",
            ["admin.configuration.menupublish.status"] = "Estado",
            ["admin.configuration.dinein.legacynoloenterpriseqrcodehash"] = "(Legado) Nolo Enterprise QR Code Hash",
            ["admin.configuration.mgs.backtolist"] = "Voltar à lista do seletor de grupo de modificadores",
            ["admin.configuration.settings.generalcommon.blocktitle.googleapi"] = "Chave GoogleApi",
            ["admin.configuration.settings.geolocation"] = "Geolocalização",
            ["admin.configuration.settings.geolocation.blocktitle.distanceradius"] = "Raio de distância",
            ["admin.configuration.settings.geolocation.blocktitle.locationdetection"] = "Detecção de localização",
            ["admin.configuration.settings.kitchencapacity"] = "Capacidade da cozinha",
            ["admin.configuration.settings.kitchencapacity.blocktitle.timeslotcapacity"] =
                "Capacidade do intervalo de tempo",
            ["admin.configuration.settings.shoppingcart.displaymenuafteraddingproduct"] =
                "Exibir menu após adicionar um produto",
            ["admin.configuration.settings.shoppingcart.displaymenuafteraddingproduct.hint"] =
                "Se marcada, o cliente será direcionado para a página do menu imediatamente após adicionar um produto ao carrinho. Se desmarcada, o cliente permanecerá na mesma página de qual o produto foi adicionado ao carrinho.",
            ["admin.configuration.settings.storescope.hint"] =
                "As configurações de 'Todas as lojas' não são exibidas na seleção de loja única",
            ["admin.configuration.spa"] = "Disponibilidade programada do produto",
            ["admin.configuration.stores.blocktitle.IdleTime"] = "Tempo ocioso",
            ["admin.configuration.stores.blocktitle.holiday"] = "Horário de funcionamento sazonal",
            ["admin.configuration.stores.blocktitle.info"] = "Informações da loja",
            ["admin.configuration.stores.blocktitle.largeordernotification"] = "Notificação de pedido grande",
            ["admin.configuration.stores.blocktitle.preordernotification"] = "Notificação de pré-encomenda",
            ["admin.configuration.stores.blocktitle.selectday"] = "Selecionar dias úteis",
            ["admin.configuration.stores.blocktitle.storepickup"] = "Retirada na loja",
            ["admin.configuration.stores.blocktitle.storetimings"] = "Horário de abertura e fechamento da loja",
            ["admin.configuration.stores.fields.IdleTime"] = "Tempo ocioso (min)",
            ["admin.configuration.stores.fields.IdleTime.hint"] = "Tempo ocioso (min)",
            ["checkout.customerinformation.saveaddress"] = "Salvar este endereço em minha lista de endereços",
            ["checkout.orderdetails.table.address"] = "Endereço da loja",
            ["clickandcollect.backtolocation"] = "Voltar",
            ["clickandcollect.maintitle"] = " QUANDO VOCÊ GOSTARIA",
            ["clickandcollect.note"] =
                "Observação: os horários de coleta podem mudar durante o processo de pedido. O horário de entrega real será confirmado durante a finalização da compra.",
            ["clickandcollect.searchtitle"] = "Clique e retire de",
            ["clickandcollect.searchtitle.FiveguysES"] = "Coletar de",
            ["clickandcollect.searchtitle.FiveguysUK"] = "Coletar de",
            ["clickandcollect.searchtitle.FiveguysDE"] = "Coletar de",
            ["clickandcollect.searchtitle.chikn"] = "Coletar de",
            ["clickandcollect.startorder"] = "INICIAR PEDIDO",
            ["clickandcollect.startorder.FiveguysES"] = "PEDIR MINHA COMIDA",
            ["clickandcollect.startorder.FiveguysUK"] = "PEDIR MINHA COMIDA",
            ["clickandcollect.startorder.FiveguysDE"] = "PEDIR MINHA COMIDA",
            ["clickandcollect.startorder.chikn"] = "PEDIR MINHA COMIDA",
            ["clickandcollect.subtitle"] = "PARA COLETAR?",
            ["clickandcollect.updatemaintitle"] = "POR FAVOR, SELECIONE UM NOVO",
            ["clickandcollect.updateorder"] = "ATUALIZAR PEDIDO",
            ["clickandcollect.updatesearchtitle"] =
                "Seu horário anterior não está mais disponível <br/> seu carrinho permanece salvo",
            ["clickandcollect.updatesubtitle"] = "HORA DA COLETA",
            ["findpostcode.enterpostcode"] = "Por favor, digite seu código postal ou área abaixo",
            ["findpostcode.error"] = "Há algum problema em seu navegador atual para obter a localização geográfica.",
            ["findpostcode.findpostcodebutton"] = "ENCONTRAR",
            ["findpostcode.findpostcodebutton.Fiveguys"] = "Encontre meus cinco caras",
            ["findpostcode.findpostcodebutton.FiveguysES"] = "Encontre meus cinco caras",
            ["findpostcode.findpostcodebutton.FiveguysUK"] = "Encontre meus cinco caras",
            ["findpostcode.findpostcodebutton.FiveguysDE"] = "Encontre meus cinco caras",
            ["findpostcode.findpostcodebutton.TacobellUK"] = "ENCONTRAR",
            ["findpostcode.findpostcodeinputplaceholder"] = "Digite seu código postal ou área",
            ["findpostcode.findpostcodeinputplaceholder.FiveguysES"] = "Digite seu CEP ou área",
            ["findpostcode.mainsubtitle"] = " RESTAURANTE",
            ["findpostcode.mainsubtitle.archiesuk"] = "",
            ["findpostcode.mainsubtitle.chikn"] = "S",
            ["findpostcode.maintitle"] = "ENCONTRE SEU LOCAL",
            ["findpostcode.mypreviousorders.fiveguys"] = "Meus pedidos anteriores",
            ["findpostcode.newcollectionfrom.fiveguys"] = "Nova coleção de",
            ["findpostcode.notfoundmessage"] =
                "Desculpe. Infelizmente, não podemos localizar nenhum restaurante nas proximidades.",
            ["findpostcode.okbutton"] = "OK",
            ["findpostcode.permissiondenied"] = "Este site não tem permissão para usar a API de geolocalização",
            ["findpostcode.permissiondeniedtimeout"] =
                "A posição atual não pôde ser determinada dentro do período de tempo limite especificado.",
            ["findpostcode.positionunavailable"] = "A posição atual não pôde ser determinada.",
            ["findpostcode.searching"] = "Pesquisando...",
            ["findpostcode.searchmaintitle"] = "Vamos começar",
            ["findpostcode.searchmaintitle.FiveguysES"] = "Evite a fila, <br/> peça online",
            ["findpostcode.searchmaintitle.FiveguysUK"] = "Pule a fila, <br/> faça o pedido online",
            ["findpostcode.searchmaintitle.FiveguysDE"] = "Pule a fila, <br/> faça o pedido online",
            ["findpostcode.searchmaintitle.Hi.fiveguys"] = "Olá",
            ["findpostcode.searchmaintitle.fiveguys"] = "Evite a fila, <br/> faça o pedido online",
            ["findpostcode.startneworderbutton.fiveguys"] = "Iniciar um novo pedido",
            ["findpostcode.storeisnowdisabled"] =
                "Lamentamos, mas esta loja não está mais disponível para pedidos online.",
            ["findpostcode.usecurrentlocation"] = "ou use minha localização",
            ["findpostcode.usecurrentlocation.TacobellUK"] = "use minha localização",
            ["findpostcode.validation"] = "Insira um código postal ou área válida",
            ["groupordering.cancelgrouporder"] = "Cancelar pedido em grupo",
            ["groupordering.cancelgrouporder.question"] = "Cancelar pedido em grupo?",
            ["groupordering.cancelgrouporder.question.subtitle"] =
                "Se você cancelar este pedido, seus convidados e seus artigos serão removidos.",
            ["groupordering.cancelgrouporder.byowner"] = "O carrinho de grupo foi cancelado pelo proprietário",
            ["groupordering.closegrouporder.byowner"] =
                "O carrinho de grupo foi fechado pelo proprietário, você não pode mais fazer alterações no pedido.",
            ["groupordering.keeporder"] = "Manter pedido",
            ["GroupOrdering.YouHaveLeft"] = "Você saiu do pedido em grupo",
            ["invalidAddress.deliverynotpossible"] = "Não fazemos entregas nesta área.",
            ["invalidAddress.okbutton"] = "OK",
            ["limiteditemswereremoved.modalbody"] =
                "Alguns itens não estão mais disponíveis para este intervalo de tempo e foram removidos de seu carrinho.",
            ["limiteditemswereremoved.modalmaintitle"] = "Alguns itens por tempo limitado foram removidos",
            ["marketplace.modalmaintitle"] = "Escolha uma opção de entrega",
            ["menu.ordersummary.collection.clickandcollect"] = "Coletar de",
            ["pedido.pedido#"] = "#",
            ["review.product.selectrating"] = "Selecione uma classificação",
            ["store.slottime"] = "(mais antigo)",
            ["storeselection.backbutton"] = "Voltar",
            ["storeselection.changelocation"] = "Alterar",
            ["storeselection.clickandcollect"] = "CLICK & COLLECT",
            ["storeselection.clickandcollect.FiveguysES"] = "COLETAR",
            ["storeselection.clickandcollect.FiveguysUK"] = "COLETAR",
            ["storeselection.clickandcollect.FiveguysDE"] = "COLETAR",
            ["storeselection.clickandcollect.chikn"] = "COLETAR",
            ["storeselection.clickandcollectPlus"] = "COLETAR+",
            ["storeselection.closed"] = "FECHADO",
            ["storeselection.curbside"] = "PICKUP CURBSIDE",
            ["storeselection.delivery"] = "ENTREGA",
            ["storeselection.deliverymarketplace"] = "Entrega de ",
            ["storeselection.findbutton"] = "ENCONTRAR",
            ["storeselection.moreinfo"] = "Mais informações",
            ["storeselection.nearrestaurant"] = "restaurante próximo a este local",
            ["storeselection.nearrestaurant.chikn"] = "loja de frango mais próxima de você",
            ["storeselection.nearrestaurants"] = "restaurantes próximos a este local",
            ["storeselection.nearrestaurants.FiveguysES"] = "Restaurantes mais próximos de sua localização",
            ["storeselection.nearrestaurants.FiveguysUK"] = "Restaurantes mais próximos de sua localização",
            ["storeselection.nearrestaurants.FiveguysDE"] = "Restaurantes mais próximos de sua localização",
            ["storeselection.nearrestaurants.chikn"] = "lojas de frango mais próximas de você",
            ["storeselection.open"] = "Abrir",
            ["storeselection.orderfrom"] = "Ou pedir de",
            ["storeselection.title.FiveguysES"] = "Seus cinco rapazes mais próximos",
            ["storeselection.title.FiveguysUK"] = "Seus cinco rapazes mais próximos",
            ["storeselection.title.FiveguysDE"] = "Seus cinco rapazes mais próximos",
            ["storeselection.title.WagamamaUK"] = "O Wagamama mais próximo",
            ["timeSlotSelection.ReservationNotAllowed"] =
                "O horário selecionado não está disponível <br/> Selecione outro",
            ["timeSlotSelection.reservationTimedOut"] = "Sua reserva expirou <br/> seu carrinho continua salvo",
            ["TimeSlotSelection.NoSlotsForSelectedDay"] = "Não há horários disponíveis para o dia selecionado.",
            ["ProductInfo.NutritionTableUnit.0"] = "Informação nutricional",
            ["ProductInfo.NutritionTableUnit.1"] = "Informação nutricional por unidade",
            ["ProductInfo.NutritionTableUnit.2"] = "Informação nutricional por 100 ml",
            ["ProductInfo.NutritionTableUnit.3"] = "Informação nutricional por 100 g",
            ["ProductInfo.SalesName"] = "Nome comercial",
            ["ProductInfo.Additives"] = "Aditivos",
            ["ProductInfo.Ingredients"] = "Ingredientes",
            ["ProductInfo.Manufacturer"] = "Fabricante",
            ["Settings.AnalyticsSettings.Edit"] = "As configurações de análise foram editadas.",
            ["Admin.Configuration.Settings.Analytics.GoogleTagManagerId"] = "ID do Google Tag Manager",
            ["Admin.Configuration.Settings.Analytics.GoogleTagManagerActive"] =
                "Ativar o rastreamento integrado do Google Tag Manager",
            ["Admin.Configuration.Settings.Analytics.GoogleTagManagerEcommerceTrackingActive"] =
                "Rastreamento de comércio eletrônico do Google Tag Manager",
            ["Admin.Configuration.Settings.Analytics"] = "Analytics",
            ["Admin.Config.Analytics.GoogleTagManager"] = "Google Tag Manager"
        };
    }

    public async Task AddLocalizations(ILocalizationService localizationService, int languageId)
    {
        await localizationService.AddOrUpdateLocaleResourceAsync(GetTerms(), languageId);
    }
}