using Nop.Services.Localization;

namespace Nxg.Web.Framework.Migrations.CustomLocalizations.Localizations;

public class RomanianLocalization : ICustomLocalization
{
    public string UniqueSeoCode => "ro";

    public Dictionary<string, string> GetTerms()
    {
        return new Dictionary<string, string>
        {
            ["generic.payment.provider.redirection.url.issue"] =
                "Adresa URL de redirecționare a furnizorului de plăți a fost goală.",
            ["Configuration.Settings.UserJourney.MinutesApartToShowAlert"] = "Minute prag de alertă automată",
            ["Configuration.Settings.UserJourney.MinutesApartToShowAlert.Hint"] =
                "Când utilizatorul este împins într-un slot care este mai mare decât această sumă în câteva minute, afișăm o alertă",
            ["Admin.Configuration.Settings.UserJourney.MinutesApartToShowAlert"] = "Minute prag de alertă automată",
            ["Admin.Configuration.Settings.UserJourney.MinutesApartToShowAlert.Hint"] =
                "Când utilizatorul este împins într-un slot care este mai mare decât această sumă în câteva minute, afișăm o alertă",
            ["Admin.Configuration.Settings.UserJourney.AutomaticallyPushUsersToNextAvailableSlot"] =
                "Impingeți utilizatorii la următorul spațiu disponibil",
            ["Admin.Configuration.Settings.UserJourney.AutomaticallyPushUsersToNextAvailableSlot.Hint"] =
                "Dacă este activat: când slotul expiră dacă un utilizator efectuează o acțiune în sistem, vom încerca să îl ducem la următorul slot disponibil, dacă este posibil, fără a întrerupe călătoria ",
            ["admin.configuration.stores.fields.storenumber"] = "Numărul magazinului",
            ["Account.AccountRemoved"] = "Your account has been removed",
            ["Account.AccountRemoved.Explanation"] =
                "You will no longer be able to login from this account or do any actions with it.",
            ["Account.AddressBook"] = "Agendă",
            ["Account.AddressBook.ViewEditAddresses"] = "Vedeți/Editați adrese",
            ["Account.AddressDetails"] = "Address Details",
            ["Account.Back"] = "Înapoi",
            ["Account.ConfirmNewPassword"] = "Reintroduceți noua parolă",
            ["Account.CustomerAddresses.AddressDetails"] = "Detalii adresa",
            ["Account.CustomerAddresses.DefaultAddress"] = "Use as default address",
            ["Account.CustomerAddresses.NoDefaultAddress"] = "No addresses yet, please add one below.",
            ["Account.CustomerOrders.PreviousOrders"] = "Comenzi anterioare",
            ["Account.CustomerVehicle.NoVehicles"] = "No Vehicles",
            ["Account.CustomerVehicles.DefaultVehicle"] = "Use as default vehicle",
            ["Account.CustomerVehicles.VehicleDetails"] = "Vehicle details",
            ["Account.DeleteAccount"] = "Delete Account",
            ["Account.DeleteAccount.Explanation"] =
                "This will delete your account in our system so you will no longer be able to login.",
            ["Account.DeleteAccount.FailedToDelete"] =
                "Failed to delete account, please make sure your password is correct.",
            ["Account.DeleteAccount.Instructions"] =
                "To delete your account please confirm your password first so we can verify it's you",
            ["Account.Fields.Email.NotValid"] = "Adresa de email nu este validă",
            ["Account.ForgotPassword.label.AutoCreated"] =
                "Ca parte a măsurilor de securitate îmbunătățite, trebuie să vă resetați parola. Aceasta înseamnă, de asemenea, că orice comenzi efectuate anterioare nu mai sunt vizibile prin pagina Conturi (deși orice comenzi noi vor fi). \r\n\r\nIntroduceți adresa de e-mail asociată contului dvs.",
            ["Account.Forgotyourpassword"] = "Forgot your password?",
            ["Account.Forgotyourpassword.AutoCreated"] = "Resetați parola",
            ["Account.Login.DontHaveAnAccount"] = "Don't have an account?",
            ["Account.Login.DontHaveAnAccount.FiveguysUK"] = "Don't have a Five Guys account?",
            ["Account.Login.DontHaveAnAccount.FiveguysDE"] = "Don't have a Five Guys account?",
            ["Account.Login.RememberMe"] = "Remember me?",
            ["Account.Login.RememberMe.FiveguysUK"] = "Remember me for next time",
            ["Account.Login.RememberMe.FiveguysDE"] = "Remember me for next time",
            ["Account.Login.RememberMe.warning"] =
                "Only enable this feature if you are certain that your device has a strong password and is safe from unauthorised access.",
            ["Account.Login.Welcome.Custom.FiveguysUK"] = "Log in to edit your account",
            ["Account.Login.Welcome.Custom.FiveguysDE"] = "Log in to edit your account",
            ["Account.Login.Welcome.FiveguysUK"] = "Welcome back",
            ["Account.Login.Welcome.FiveguysDE"] = "Welcome back",
            ["Account.Login.Welcome.GO.Custom"] = "You must be logged in to start a new group order.",
            ["Account.Login.WrongCredentials.AutoCreatedAccount.part1"] =
                "Trebuie să vă resetați parola înainte de a putea continua. Vă rugăm ",
            ["Account.Login.WrongCredentials.AutoCreatedAccount.part2"] = "dați clic aici ",
            ["Account.Login.WrongCredentials.AutoCreatedAccount.part3"] = "pentru a vă reseta parola.",
            ["Account.Marketing"] = "Marketing",
            ["Account.Marketing.SendMe"] = "Send me great deals and relevant news.",
            ["Account.Marketing.SendMe.FiveguysUK"] = "Send me great deals and relevant news about Five Guys.",
            ["Account.Marketing.SendMe.FiveguysDE"] = "Send me great deals and relevant news about Five Guys.",
            ["Account.MyAccount"] = "My Account",
            ["Account.MyAccount.WeMissedYou"] = "Ne-a fost dor de tine.",
            ["Account.MyAccount.Welcomeback"] = "Bine ați venit înapoi",
            ["Account.NewPassword"] = "Introduceți noua parolă",
            ["Account.OldPassword"] = "Introduceți parola curentă",
            ["Account.Orders"] = "Comenzi",
            ["Account.PasswordRecovery.RecoverButton.AutoCreated"] = "Resetați parola",
            ["Account.RecoverPassword.Instructions"] =
                "An email has been sent to you with a link to reset your password. Please checkyour spam folder if you do not receive the email shortly.",
            ["Account.Register.Warning"] =
                "We use the information you gave us here to process your order. To find out more information about how and why we use this information, please see our privacy policy.",
            ["Account.Register.Warning.FiveguysUK"] =
                "We use the information you gave us here to process your order. To find out more information about how and why we use this information, please see our <a target=\"_blank\" href=\"https://fiveguys.co.uk/privacy-policy/\">Privacy Policy</a>",
            ["Account.Register.Warning.FiveguysDE"] =
                "We use the information you gave us here to process your order. To find out more information about how and why we use this information, please see our <a target=\"_blank\" href=\"https://fiveguys.co.uk/privacy-policy/\">Privacy Policy</a>",
            ["Account.RemoveAddress"] = "Ștergeți adresa?",
            ["Account.RemoveVehicle"] = "Remove Vehicle",
            ["Account.Security"] = "Securitate",
            ["Account.VehicleDetails"] = "Vehicle Details",
            ["Account.VehicleDetails.NoVehicles"] = "No vehicles yet, please add one below.",
            ["Account.VehicleDetails.ViewEditVehicles"] = "View / Edit Vehicles",
            ["Account.View"] = "Vizualizare",
            ["Account.ViewPreviousOrders"] = "Vedeți toate comenzile anterioare",
            ["Account.YourAddresses"] = "Adresele dvs",
            ["Account.YourDetails"] = "Your Details",
            ["Account.YourLast"] = "Ultimul tău",
            ["ActivityLog.AddNewEmailConfiguration"] = "A new Email configuration was created (ID = {0})",
            ["ActivityLog.AddNewMGS"] = "A new modifier group selector was created: {0}",
            ["ActivityLog.AddNewSpa"] = "A fost adăugat un nou disponibilitatea programată a produsului",
            ["ActivityLog.DeleteCustomerAccount"] = "Customer deleted his/her account (ID = {0})",
            ["ActivityLog.DeleteEmailConfiguration"] = "An Email configuration was deleted (ID = {0})",
            ["ActivityLog.EditEmailConfiguration"] = "An Email configuration was updated (ID = {0})",
            ["Address.City"] = "Oraș",
            ["Address.Email"] = "E-mail",
            ["Address.Firstname"] = "Prenumele",
            ["Address.Lastname"] = "Nume",
            ["Address.Phonenumber"] = "Număr de telefon",
            ["Address.Streetaddress1"] = "Adresa 1",
            ["Address.Streetaddress2"] = "Adresa stradă 2",
            ["Address.ZipPostalCode"] = "Poștal / Cod poștal",
            ["Admin.Catalog.Attributes.ProductAttributes.Fields.IncludeInNoToppingsModalCheck"] =
                "Include these modifiers in the check for the 'No Toppings' modal",
            ["Admin.Catalog.Attributes.ProductAttributes.Fields.IncludeInNoToppingsModalCheck.Hint"] =
                "Modifiers of this product attribute type will be checked if any is selected on the add to order action, if not the modal 'No toppings' is shown.",
            ["Admin.Catalog.Attributes.ProductAttributes.Fields.ShowProductInformationButton"] =
                "Afișați butonul de informații despre produs pe valorile atributului",
            ["Admin.Catalog.Attributes.ProductAttributes.Fields.ShowProductInformationButton.Hint"] =
                "Un buton pe fiecare valoare de atribut care va deschide o fereastră pop-up atunci când este clic, care conține informațiile nutriționale ale atributului.",
            ["Admin.Catalog.Attributes.ProductAttributes.Fields.MaxSelectedAttributeCount"] =
                "Maximum number of attribute values that can be selected",
            ["Admin.Catalog.Attributes.ProductAttributes.Fields.MaxSelectedAttributeCount.Hint"] =
                "The maximum number of attribute values that can be selected for this attribute",
            ["Admin.Catalog.Attributes.ProductAttributes.Fields.MinSelectedAttributeCount"] =
                "Minimum number of attribute values that can be selected",
            ["Admin.Catalog.Attributes.ProductAttributes.Fields.MinSelectedAttributeCount.Hint"] =
                "The minimum number of attribute values that can be selected for this attribute",
            ["Admin.Catalog.Delivery.DeliveryTimings.BackToStore"] = "înapoi la livrare",
            ["Admin.Catalog.Delivery.DeliveryTimings.EditDeliveryTimingsDetails"] =
                "Editați detaliile termenului de livrare",
            ["Admin.Catalog.Delivery.DeliveryTimings.SelectBeforeEdit"] =
                "Vă rugăm să selectați mai întâi zilele de livrare",
            ["Admin.Catalog.KitchenCapacity.Timings.Alert.AddNew"] = "Toate campurile sunt necesare.",
            ["Admin.Catalog.KitchenCapacity.editkitchencapacitydetails"] = "Editați detaliile capacității bucătăriei",
            ["Admin.Catalog.MGS.AddedSuccessfully"] = "Modifier group selector created successfully",
            ["Admin.Catalog.MGS.Fields.CreatedOnUTC"] = "Created at",
            ["Admin.Catalog.MGS.Fields.DisplayName"] = "Display Name (client face)",
            ["Admin.Catalog.MGS.Fields.Name"] = "Name",
            ["Admin.Catalog.MGS.Fields.Products"] = "Products",
            ["Admin.Catalog.MGS.Fields.ProductsModifiers"] = "Modifiers",
            ["Admin.Catalog.MGS.UpdatedSuccessfully"] = "Modifier group selected was updated successfully",
            ["Admin.Catalog.MSG.AddButton"] = "Add Modifiers Group Selector",
            ["Admin.Catalog.Products.Fields.Allergens"] = "Allergens",
            ["Admin.Catalog.Products.Fields.FixedQuantitiesSKU"] = "Fixed Quantitites SKU",
            ["Admin.Catalog.Products.Fields.FixedQuantitiesSKU.Hint"] =
                "Full SKU including Fixed Quantitites Properties",
            ["Admin.Catalog.Products.Fields.Nutrition"] = "Nutrition",
            ["Admin.Catalog.Products.Fields.RestrictedStores"] = "Magazine",
            ["Admin.Catalog.Products.Fields.RestrictedStores.Hint"] =
                "Opțiune de a restricționa/elimina acest produs la/din anumite magazine. " +
                "Dacă aveți mai multe magazine, alegeți unul sau mai multe din listă. " +
                "Dacă nu utilizați această opțiune, lăsați acest câmp necompletat. " +
                "Pentru a utiliza această funcționalitate, trebuie să dezactivați următoarea setare: " +
                "Configurare > Setări catalog > Ignorați regulile „limită per magazin” (la nivel de site).",
            ["Admin.Catalog.Products.Fields.StoreRestrictionMode"] = "Mod restricționare",
            ["Admin.Catalog.Products.Fields.VariantDisplayType"] = "Variant display type",
            ["Admin.Catalog.Products.Fields.VariantDisplayType.Hint"] =
                "How the variants will be presented in the grouped product page (buttons, checkboxes)",
            ["Admin.Catalog.Products.ProductOrderTypeMapping"] = "Available order types",
            ["Admin.Catalog.Products.ProductOrderTypeMapping.AddNew"] = "Add new order type mapping",
            ["Admin.Catalog.Products.ProductOrderTypeMapping.Fields.OrderType"] = "Order Type",
            ["Admin.Catalog.Products.ProductOrderTypeMapping.Fields.Store"] = "Store",
            ["Admin.Catalog.Products.ProductOrderTypeMapping.Hint"] =
                "Specify for what type of order (and optionally store) this product is available in",
            ["Admin.Catalog.Products.ProductPerOrderType"] = "Order Types",
            ["Admin.Catalog.Products.TierPrices.Fields.OrderType"] = "Order Type",
            ["Admin.Catalog.Products.Variants.DisplayType.Buttons"] = "Buttons",
            ["Admin.Catalog.Products.Variants.DisplayType.Checkboxes"] = "Checkboxes",
            ["Admin.Catalog.Store.Holiday.Alert.HolidayAdd"] = "Nu s-a putut adăuga vacanță.",
            ["Admin.Catalog.Store.Holiday.SaveBeforeEdit"] =
                "Trebuie să salvați magazinul înainte de a putea adăuga vacanță pentru această pagină de magazin.",
            ["Admin.Catalog.Store.StoreTimings.EditStoreTimingsDetails"] = "Editați detaliile orelor magazinului",
            ["Admin.Catalog.Store.Timings.Alert.TimingsAdd"] = "Nu s-au adăugat orele de deschidere și de închidere.",
            ["Admin.Catalog.Store.Timings.SaveBeforeEdit"] =
                "Trebuie să salvați magazinul înainte de a putea adăuga orare pentru această pagină de magazin.",
            ["Admin.Config.UserJourney.Cart"] = "Cart Section Page",
            ["Admin.Config.UserJourney.CheckoutPage"] = "Checkout page",
            ["Admin.Config.UserJourney.Homepage"] = "Home Page",
            ["Admin.Config.UserJourney.MenuPage"] = "Menu Page",
            ["Admin.Config.UserJourney.ProcessingPaymentPage"] = "Processing Payment Page",
            ["Admin.Config.UserJourney.ProductPage"] = "Product Page",
            ["Admin.Config.UserJourney.StoreSelection"] = "Store Selection Page",
            ["Admin.Config.UserJourney.TimeSlotSelectionPage"] = "Time Slot Selection Page",
            ["Admin.Configuration.AppSettings.RedisConfigNxg"] = "Redis configuration",
            ["Admin.Configuration.AppSettings.RedisConfigNxg.ConnectionString"] = "Connection string",
            ["Admin.Configuration.AppSettings.RedisConfigNxg.Prefix"] = "Prefix for redis keys",
            ["Admin.Configuration.AppSettings.RedisConfigNxg.Prefix.Hint"] =
                "String prefix we want to put on the redis keys so it does not collide with other environments using the same redis instance",
            ["Admin.Configuration.Catalog.MenuManager"] = "Editor Menu Manager",
            ["Admin.Configuration.Catalog.ModifiersGroupSelector"] = "Modifiers Group Selector",
            ["Admin.Configuration.Customers.ImportFromCsv"] = "Import customers from CSV",
            ["Admin.Configuration.Delivery.BlockTitle.DeliveryTimings"] = "Orele de livrare",
            ["Admin.Configuration.Delivery.BlockTitle.SelectDay"] = "Selectați zilele de livrare",
            ["Admin.Configuration.Delivery.DeletedTiming"] = "Timpul de livrare a fost șters cu succes.",
            ["Admin.Configuration.Delivery.DeliveryDetails"] = "Detalii de livrare",
            ["Admin.Configuration.Delivery.UpdatedTiming"] = "Timpul de livrare a fost actualizat cu succes.",
            ["Admin.Configuration.DineIn"] = "Luați masa",
            ["Admin.Configuration.DineIn.BackToDineIn"] = "Înapoi la Dine In",
            ["Admin.Configuration.DineIn.IsDineInEnabled"] = "Activat?",
            ["Admin.Configuration.DineIn.QRCodeForStore"] = "Codul QR al magazinului: ",
            ["Admin.Configuration.DineIn.QRcode"] = "Cod QR",
            ["Admin.Configuration.DineIn.Store"] = "Magazin",
            ["Admin.Configuration.DineIn.Tables"] = "Tabele",
            ["Admin.Configuration.DineIn.Url"] = "URL",
            ["Admin.Configuration.EmailAccounts.Deleted"] = "The Email configuration was deleted",
            ["Admin.Configuration.EmailConfiguration"] = "Email configuration",
            ["Admin.Configuration.EmailConfiguration.BackToList"] = "Back to Email configuration list",
            ["Admin.Configuration.EmailConfiguration.CreateTitle"] = "Add new Email configuration",
            ["Admin.Configuration.EmailConfiguration.DisplayName"] = "Name",
            ["Admin.Configuration.EmailConfiguration.EditTitle"] = "Edit Email configuration",
            ["Admin.Configuration.EmailConfiguration.EmailAddress"] = "Email address",
            ["Admin.Configuration.EmailConfiguration.General"] = "General",
            ["Admin.Configuration.GeoLocation.Marketplaces.AddButton"] = "Adăugați piață",
            ["Admin.Configuration.GeoLocation.Marketplaces.AddNew"] = "Adăugați piață",
            ["Admin.Configuration.GeoLocation.Marketplaces.AddedSuccessfully"] = "Piața a fost adăugată cu succes.",
            ["Admin.Configuration.GeoLocation.Marketplaces.BackToGeoLocation"] = "înapoi la geolocație",
            ["Admin.Configuration.GeoLocation.Marketplaces.EditAttributeDetails"] = "Editați detaliile pieței",
            ["Admin.Configuration.GeoLocation.Marketplaces.Fields.Name.Required"] = "vă rugăm să furnizați un nume",
            ["Admin.Configuration.GeoLocation.Marketplaces.Link"] = "Link",
            ["Admin.Configuration.GeoLocation.Marketplaces.Logo"] = "Sigla",
            ["Admin.Configuration.GeoLocation.Marketplaces.Name"] = "Nume",
            ["Admin.Configuration.GeoLocation.Marketplaces.NotExist"] =
                "Nu a fost găsit nicio piață cu id-ul specificat",
            ["Admin.Configuration.GeoLocation.Marketplaces.RadiusDistance"] = "Distanța pe rază",
            ["Admin.Configuration.GeoLocation.Marketplaces.UnitOfMeasurement"] = "Unitate de măsură",
            ["Admin.Configuration.GeoLocation.Marketplaces.UpdatedSuccessfully"] =
                "Piața a fost actualizată cu succes.",
            ["Admin.Configuration.KitchenCapacity.Fields.SizeOfSlot"] = "Dimensiunea slotului (min)",
            ["Admin.Configuration.KitchenCapacity.Fields.SizeOfSlot.hint"] = "Dimensiunea slotului",
            ["Admin.Configuration.KitchenCapacity.Fields.SlotCapacity"] = "Capacitatea slotului",
            ["Admin.Configuration.KitchenCapacity.Fields.SlotCapacity.hint"] = "Capacitatea slotului",
            ["Admin.Configuration.KitchenCapacity.Fields.SlotReservation"] = "Rezervare slot",
            ["Admin.Configuration.KitchenCapacity.Fields.SlotReservation.hint"] = "Rezervare slot",
            ["Admin.Configuration.KitchenCapacity.ImportFromCsv"] = "Import working days from CSV",
            ["Admin.Configuration.KitchenCapacity.OverlappingConfigurations"] =
                "Modificările de configurare solicitate se suprapun cu timpul curent pentru ziua selectată. Vă rugăm să remediați și să încercați din nou.",
            ["Admin.Configuration.MGS.NotExist"] = "Modifier group selector does not exist",
            ["Admin.Configuration.Settings.Catalog.AllergensAndNutrients"] = "Alergeni și nutrienți",
            ["Admin.Configuration.Settings.Catalog.AllergensAndNutrients.Hint"] =
                "Bifați pentru a activa afișarea nutrienților și alergenilor produsului",
            ["Admin.Configuration.Settings.Catalog.AllergensAndNutrientsModal"] = "Allergens and Nutrients Modal",
            ["Admin.Configuration.Settings.Catalog.AllergensAndNutrientsModal.Hint"] =
                "Check to display of product's nutrients and allergens within a modal instead of in PDF",
            ["Admin.Configuration.Settings.CustomerUser.AddressFormFields.CityJustForDelivery"] =
                "Activați configurația orașului numai la livrare",
            ["Admin.Configuration.Settings.CustomerUser.AddressFormFields.CityJustForDelivery.Hint"] =
                "Când este bifat, înseamnă că configurația de mai sus va fi aplicată numai comenzilor de tipul de livrare.",
            ["Admin.Configuration.Settings.CustomerUser.AddressFormFields.CountryJustForDelivery"] =
                "Activați configurația țării numai la livrare",
            ["Admin.Configuration.Settings.CustomerUser.AddressFormFields.CountryJustForDelivery.Hint"] =
                "Când este bifat, înseamnă că configurația de mai sus va fi aplicată numai comenzilor de tipul de livrare.",
            ["Admin.Configuration.Settings.CustomerUser.AddressFormFields.CountyJustForDelivery"] =
                "Activați configurația județului numai la livrare",
            ["Admin.Configuration.Settings.CustomerUser.AddressFormFields.CountyJustForDelivery.Hint"] =
                "Când este bifat, înseamnă că configurația de mai sus va fi aplicată numai comenzilor de tipul de livrare.",
            ["Admin.Configuration.Settings.CustomerUser.AddressFormFields.StateProvinceJustForDelivery"] =
                "Activați configurația de stat/province numai la livrare",
            ["Admin.Configuration.Settings.CustomerUser.AddressFormFields.StateProvinceJustForDelivery.Hint"] =
                "Când este bifat, înseamnă că configurația de mai sus va fi aplicată numai comenzilor de tipul de livrare.",
            ["Admin.Configuration.Settings.CustomerUser.AddressFormFields.StreetAddress2JustForDelivery"] =
                "Activați configurația Street Address 2 numai la livrare",
            ["Admin.Configuration.Settings.CustomerUser.AddressFormFields.StreetAddress2JustForDelivery.Hint"] =
                "Când este bifat înseamnă că configurația de mai sus va fi aplicată numai comenzilor de tipul de livrare.",
            ["Admin.Configuration.Settings.CustomerUser.AddressFormFields.StreetAddressJustForDelivery"] =
                "Activați configurarea adresei stradale numai la livrare",
            ["Admin.Configuration.Settings.CustomerUser.AddressFormFields.StreetAddressJustForDelivery.Hint"] =
                "Când este bifat, înseamnă că configurația de mai sus va fi aplicată numai comenzilor de tipul de livrare.",
            ["Admin.Configuration.Settings.CustomerUser.AddressFormFields.ZipPostalCodeJustForDelivery"] =
                "Activați configurarea codului poștal numai la livrare",
            ["Admin.Configuration.Settings.CustomerUser.AddressFormFields.ZipPostalCodeJustForDelivery.Hint"] =
                "Când este bifat înseamnă că configurația de mai sus va fi aplicată numai comenzilor de tipul de livrare.",
            ["Admin.Configuration.Settings.DeliverySettings"] = "Livrare",
            ["Admin.Configuration.Settings.GeneralCommon.CaptchaShowOnGuestCheckoutPage"] =
                "Afișați pe pagina de plată pentru oaspeți",
            ["Admin.Configuration.Settings.GeneralCommon.CaptchaShowOnGuestCheckoutPage.Hint"] =
                "Bifați pentru a afișa CAPTCHA la finalizarea oaspeților.",
            ["Admin.Configuration.Settings.GeneralCommon.DisplayDefaultFooterItemSettingsModel.DisplayPoweredByLinetenFooterItem"] =
                "Afişa \"Powered by Lineten\"",
            ["Admin.Configuration.Settings.GeneralCommon.DisplayDefaultFooterItemSettingsModel.DisplayPoweredByLinetenFooterItem.Hint"] =
                "Bifați pentru a afișa \"Powered by Lineten\" în subsol",
            ["Admin.Configuration.Settings.GeneralCommon.GoogleApiKey"] = "Cheie GoogleApi",
            ["Admin.Configuration.Settings.GeneralCommon.OneTrustScript"] = "One Trust Script",
            ["Admin.Configuration.Settings.GeneralCommon.OneTrustScript.Hint"] =
                "Paste here the One Trust script to embed in this site",
            ["Admin.Configuration.Settings.GeoLocation.BlockTitle.Marketplaces"] = "MarketPlaces",
            ["Admin.Configuration.Settings.GeoLocation.ClickCollect"] = "Click & Collect",
            ["Admin.Configuration.Settings.GeoLocation.Curbside"] = "Curbside",
            ["Admin.Configuration.Settings.GeoLocation.Delivery"] = "Livrare",
            ["Admin.Configuration.Settings.GeoLocation.EngineTimeout"] = "Timp de expirare a motorului (secunde)",
            ["Admin.Configuration.Settings.GeoLocation.UnitMeasurement"] = "Unitate de măsură",
            ["Admin.Configuration.Settings.MenuManager"] = "Menu Manager",
            ["Admin.Configuration.Settings.MenuManager.InvalidUrl"] = "URL invalid",
            ["Admin.Configuration.Settings.MenuManager.Url"] = "URL",
            ["Admin.Configuration.Settings.Order.BlockTitle.Type"] = "Tipuri de comenzi",
            ["Admin.Configuration.Settings.Order.ClickAndCollectNotes"] = "Click and Collect Notes",
            ["Admin.Configuration.Settings.Order.ClickAndCollectNotes.Hint"] =
                "Notes to display when click and collect is available (leave empty if no notes are to be shown).",
            ["Admin.Configuration.Settings.Order.Click_Collect"] = "Click&Collect",
            ["Admin.Configuration.Settings.Order.Click_CollectEnabled"] = "Click&Collect",
            ["Admin.Configuration.Settings.Order.Curbside"] = "Curbside",
            ["Admin.Configuration.Settings.Order.CurbsideEnabled"] = "Curbside",
            ["Admin.Configuration.Settings.Order.CurbsideNotes"] = "Curbside Notes",
            ["Admin.Configuration.Settings.Order.CurbsideNotes.Hint"] =
                "Notes to display when curbside is available (leave empty if no notes are to be shown).",
            ["Admin.Configuration.Settings.Order.Days"] = "Fereastra de colectare a programului (zile)",
            ["Admin.Configuration.Settings.Order.Delivery"] = "Livrare",
            ["Admin.Configuration.Settings.Order.DeliveryEnabled"] = "Livrare",
            ["Admin.Configuration.Settings.Order.DeliveryNotes"] = "Delivery Notes",
            ["Admin.Configuration.Settings.Order.DeliveryNotes.Hint"] =
                "Notes to display when delivery is available (leave empty if no notes are to be shown).",
            ["Admin.Configuration.Settings.Order.DineInEnabled"] = "Dine In (Tabel)",
            ["Admin.Configuration.Settings.Order.DisplayOrderNotes"] = "Afișați caseta de note de comandă",
            ["Admin.Configuration.Settings.Order.GroupOrderingEnabled"] = "Group Ordering",
            ["Admin.Configuration.Settings.Order.LeadTimeClickCollectEnabled"] = "Timp de livrare C&C (min)",
            ["Admin.Configuration.Settings.Order.LeadTimeDineInEnabled"] = "Timpul de Așteptare la Masa (min)",
            ["Admin.Configuration.Settings.Order.LeadTimeDeliveryEnabled"] = "Timp de livrare (min)",
            ["Admin.Configuration.Settings.Order.LeadTimeGroupOrder"] = "Lead Time Group Order (min)",
            ["Admin.Configuration.Settings.Order.MarketPlaceEnabled"] = "Maketplaces",
            ["Admin.Configuration.Settings.Order.MarketPlaceNotes"] = "Marketplace Notes",
            ["Admin.Configuration.Settings.Order.MarketPlaceNotes.Hint"] =
                "Notes to display when marketplaces are available (leave empty if no notes are to be shown).",
            ["Admin.Configuration.Settings.Order.MaxOrderTotalAmount"] = "Max order total amount",
            ["Admin.Configuration.Settings.Order.MaxOrderTotalAmount.Hint"] = "Enter maximum order total amount",
            ["Admin.Configuration.Settings.Order.OrderNotesLength"] = "Lungimea maximă a notelor de comandă",
            ["Admin.Configuration.Settings.OrderTypes"] = "Tipuri de comenzi",
            ["Admin.Configuration.Settings.Spa"] = "Timp limitat",
            ["Admin.Configuration.Settings.UserJourney"] = "Călătoria Utilizatorului",
            ["Admin.Configuration.Settings.UserJourney.ChangeLocationOnMobile"] =
                "Afișează câmpul de modificare a locației pe mobil",
            ["Admin.Configuration.Settings.UserJourney.ChangeLocationOnMobile.Hint"] =
                "Când este activat, câmpul de introducere pentru modificarea locației apare pe versiunea mobilă, altfel nu este afișat nimic",
            ["Admin.Configuration.Settings.UserJourney.DisplayDeliveriesAsModal"] =
                "Afișați piețele externe de livrare într-un mod",
            ["Admin.Configuration.Settings.UserJourney.DisplayDeliveriesAsModal.Hint"] =
                "Când este activat, toate piețele sunt afișate într-un modal, nu în cardurile magazinului",
            ["Admin.Configuration.Settings.UserJourney.DisplayKCalInModifiers"] = "Display calories on modifiers",
            ["Admin.Configuration.Settings.UserJourney.DisplayKCalInModifiers"] = "Display kcal in modifiers",
            ["Admin.Configuration.Settings.UserJourney.DisplayKCalInModifiers.Hint"] =
                "Enabled starts displaying kcal in modifiers",
            ["Admin.Configuration.Settings.UserJourney.DisplayKCalInModifiers.Hint"] =
                "When enable the nutrional calorie value (if there's one) will appear on the modifiers",
            ["Admin.Configuration.Settings.UserJourney.DisplayKCalInProductDescription"] =
                "Display kcal in product's description",
            ["Admin.Configuration.Settings.UserJourney.DisplayKCalInProductDescription.Hint"] =
                "Enabled starts displaying kcal in product's description",
            ["Admin.Configuration.Settings.UserJourney.DisplayKjInProductNutritionInfo"] =
                "Afișați valoarea kcal / kj în informațiile nutriționale ale produsului",
            ["Admin.Configuration.Settings.UserJourney.DisplayKjInProductNutritionInfo.Hint"] =
                "Afișați valoarea kj în concordanță cu valoarea kcal în prima linie a tabelului de informații nutriționale ale produsului",
            ["Admin.Configuration.Settings.UserJourney.DisplayKCalInProductDescriptionDisplayType"] =
                "Display type for the product's kcal on the description",
            ["Admin.Configuration.Settings.UserJourney.DisplayMarketingEmailsOption"] =
                "Show marketing emails selection",
            ["Admin.Configuration.Settings.UserJourney.DisplayMarketingEmailsOption.Hint"] =
                "When active in the checkout form the users are able to select if they want to receive marketing emails",
            ["Admin.Configuration.Settings.UserJourney.DisplayPriceInModifiers"] = "Afișați prețurile în modificatori",
            ["Admin.Configuration.Settings.UserJourney.DisplayPriceInModifiers.Hint"] =
                "Dacă este activat în lista de modificatori, prețul va fi afișat lângă fiecare modificator, dacă este cazul.",
            ["Admin.Configuration.Settings.UserJourney.HideRadioPriceAdjustment"] = "Hide radio price adjustment",
            ["Admin.Configuration.Settings.UserJourney.HideRadioPriceAdjustment.Hint"] =
                "When enabled it hides the price adjustment on modifiers of radio type",
            ["Admin.Configuration.Settings.UserJourney.HideUpSellsInProductPage"] = "Hide upsells in product page",
            ["Admin.Configuration.Settings.UserJourney.HideUpSellsInProductPage.Hint"] =
                "Enabled will hide upsells on product pages",
            ["Admin.Configuration.Settings.UserJourney.ModifiersSeparator"] =
                "Modificatori separator în mod implicit este <br/>  (o întrerupere de linie)",
            ["Admin.Configuration.Settings.UserJourney.ModifiersSeparator.Hint"] =
                "Setați acest lucru la ceea ce doriți să utilizați pentru a separa modificatorii câteva exemple: ' | ', ' , ', '<br/>', ' ; ' ",
            ["Admin.Configuration.Settings.UserJourney.NoToppingsModalEnabled"] = "Activate the 'No Toppings' modal",
            ["Admin.Configuration.Settings.UserJourney.NoToppingsModalEnabled.Hint"] =
                "When enabled it shows a modal to users that don't select any modifiers in the product",
            ["Admin.Configuration.Settings.UserJourney.OrderTotalWithinButton"] =
                "Faceți afișarea totală a comenzii de produs în butonul de adăugare la comandă.",
            ["Admin.Configuration.Settings.UserJourney.OrderTotalWithinButton.Hint"] =
                "Când este activat, totalul produsului (modificatoare incluse) apare în butonul de adăugare la comandă, altfel apare într-o linie deasupra acestuia.",
            ["Admin.Configuration.Settings.UserJourney.ProcessingPaymentPageTimeout"] =
                "Timeout on processing your order page (minutes)",
            ["Admin.Configuration.Settings.UserJourney.ProcessingPaymentPageTimeout.Hint"] =
                "By default the value is 5 minutes.",
            ["Admin.Configuration.Settings.UserJourney.ProductReviews"] = "Product Reviews",
            ["Admin.Configuration.Settings.UserJourney.ProductReviews.Hint"] =
                "When enabled reviews are turned on and when disabled reviews are off",
            ["Admin.Config.UserJourney.CorporatePage"] = "Pagina corporativă",
            ["Admin.Configuration.Settings.UserJourney.ShowCorporatePagePopup"] = "Afișează pop-up",
            ["Admin.Configuration.Settings.UserJourney.ShowCorporatePagePopup.Hint"] =
                "Se afișează un pop-up la intrarea pe pagina corporativă. Apare o singură dată pe sesiune",
            ["Admin.Configuration.Settings.UserJourney.CorporatePagePopupContent"] = "Conținutul pop-up-ului",
            ["Admin.Configuration.Settings.UserJourney.CorporatePagePopupContent.Hint"] =
                "Conținutul pop-up-ului (poate fi HTML simplu)",
            ["Admin.Configuration.Settings.UserJourney.RecommendedIntakeText"] = "Recommended intake text",
            ["Admin.Configuration.Settings.UserJourney.ShowAllergensInformationModal"] =
                "Afișează fereastra modală cu informații despre alergeni",
            ["Admin.Configuration.Settings.UserJourney.ShowAllergensInformationModal.Hint"] =
                "Afișează o fereastră modală care conține informații despre alergeni de fiecare dată când un utilizator accesează pagina de meniu",
            ["Admin.Configuration.Settings.UserJourney.AllergensInformationModalGuidelineUrl"] =
                "URL-ul ferestrei modale cu informații despre alergeni",
            ["Admin.Configuration.Settings.UserJourney.AllergensInformationModalGuidelineUrl.Hint"] =
                "Va adăuga un buton la sfârșitul ferestrei modale dacă este configurat.",
            ["Admin.Configuration.Settings.UserJourney.AllowStoreAndTimeslotChange"] =
                "Buton de schimbare a magazinului",
            ["Admin.Configuration.Settings.UserJourney.AllowStoreAndTimeslotChange.Hint"] =
                "Acest buton vă permite să schimbați magazinul fără a fi nevoie să parcurgeți procesul de selectare a intervalului de timp.",
            ["Admin.Configuration.Settings.UserJourney.ShowProductInformationButton"] =
                "Afișați butonul de informații despre produs",
            ["Admin.Configuration.Settings.UserJourney.ShowProductInformationButton.Hint"] =
                "Un buton pe fiecare carte de produs care va deschide o fereastră pop-up atunci când este clic, care conține informații nutriționale despre produs.",
            ["Admin.Configuration.Settings.UserJourney.HideCategoryImageInMenuPage"] = "Ascunde imaginea categoriei",
            ["Admin.Configuration.Settings.UserJourney.HideCategoryImageInMenuPage.Hint"] =
                "Ascunde imaginea categoriei în antetul categoriei din pagina de meniu",
            ["Admin.Configuration.Settings.UserJourney.SkipHomePage"] = "Omiteți pagina de pornire",
            ["Admin.Configuration.Settings.UserJourney.SkipHomePage.Hint"] =
                "Dacă este activată, pagina de pornire nu se va afișa, în schimb utilizatorul este redirecționat către pagina de găsire a codului meu poștal.",
            ["Admin.Configuration.Settings.UserJourney.SlotDisplayDateTimeFormat"] =
                "Datetime format (override) for the time slot display",
            ["Admin.Configuration.Settings.UserJourney.SlotDisplayDateTimeFormat.Hint"] =
                "When empty we display (today, monday, tuesday, etc.) if you want to display something like (today, monday 1st, tuesday 2nd) add into the format of the date like dddd P. dddd is the week day and P is the day of the month with suffix",
            ["Admin.Configuration.Settings.UserJourney.UseMarketingOptOut"] = "Marketing opt out",
            ["Admin.Configuration.Settings.UserJourney.UseMarketingOptOut.Hint"] = "Enabling marketing as opt out",
            ["Admin.Configuration.Spa.AddButton"] = "Adăugați disponibilitatea programată a produsului",
            ["Admin.Configuration.Spa.AddNew"] = "Adăugați un disponibilitatea programată a produsului",
            ["Admin.Configuration.Spa.AddedSuccessfully"] = "Nouă perioadă limitată adăugată",
            ["Admin.Configuration.Spa.BackToList"] = "Înapoi la lista cu durată limitată",
            ["Admin.Configuration.Spa.EditAttributeDetails"] =
                "Editați detaliile pe disponibilitatea programată a produsului",
            ["Admin.Configuration.Spa.Fields.CreatedOnUTC"] = "Creat la",
            ["Admin.Configuration.Spa.Fields.DisplayProductWhenNotAvailable"] = "Întotdeauna vizibil",
            ["Admin.Configuration.Spa.Fields.DisplayProductWhenNotAvailable.Hint"] =
                "Când este activat, chiar dacă intervalul de timp nu este în acest timp limitat, produsul va fi afișat în meniu ca indisponibil.",
            ["Admin.Configuration.Spa.Fields.Name"] = "Nume",
            ["Admin.Configuration.Spa.Fields.NumberOfAssociatedProducts"] = "Număr de produse",
            ["Admin.Configuration.Spa.Fields.StoreId"] = "Magazin",
            ["Admin.Configuration.Spa.NotExist"] =
                "Nu s-a găsit niciun disponibilitatea programată a produsului cu id-ul specificat",
            ["Admin.Configuration.Spa.Timings"] = "Timp de disponibilitatea programată a produsului",
            ["Admin.Configuration.Spa.Timings.AddButton"] = "Adăugați un nou timp",
            ["Admin.Configuration.Spa.Timings.AddNew"] = "Adăugați un nou timp",
            ["Admin.Configuration.Spa.Timings.Alert.AddNew"] = "Toate câmpurile sunt obligatorii.",
            ["Admin.Configuration.Spa.Timings.Alert.TimingsAdd"] =
                "Eșuat la adăugarea orelor de deschidere și de închidere.",
            ["Admin.Configuration.Spa.Timings.BackToSpa"] = "Înapoi la disponibilitatea programată a produsului",
            ["Admin.Configuration.Spa.Timings.EditTimingsDetails"] =
                "Editați detaliile de disponibilitatea programată a produsului",
            ["Admin.Configuration.Spa.Timings.Fields.DayId"] = "Ziu",
            ["Admin.Configuration.Spa.Timings.Fields.DayIdError"] = "Ziu nevalidă",
            ["Admin.Configuration.Spa.Timings.Fields.EndTime"] = "Ora de încheiere",
            ["Admin.Configuration.Spa.Timings.Fields.EndTimeError"] = "Ora de încheiere nevalidă",
            ["Admin.Configuration.Spa.Timings.Fields.StartTime"] = "Ora de începere",
            ["Admin.Configuration.Spa.Timings.Fields.StartTimeError"] = "Ora de pornire nevalidă",
            ["Admin.Configuration.Spa.Timings.SaveBeforeEdit"] =
                "Trebuie să economisiți acest disponibilitatea programată a produsului înainte de a putea adăuga timpi pentru el.",
            ["Admin.Configuration.Spa.UpdatedSuccessfully"] = "Timp limitat actualizat cu succes.",
            ["Admin.Configuration.Stores.AgentCommentLabel"] = "Agent Comment",
            ["Admin.Configuration.Stores.AgentCommentTitle"] = "Please insert a justification below",
            ["Admin.Configuration.Stores.Disabled"] = " was disabled ",
            ["Admin.Configuration.Stores.Enabled"] = " was enabled ",
            ["Admin.Configuration.Stores.Fields.Date"] = "Data",
            ["Admin.Configuration.Stores.Fields.Date.hint"] = "Data",
            ["Admin.Configuration.Stores.Fields.DayId"] = "Ziu",
            ["Admin.Configuration.Stores.Fields.DayId.hint"] = "Numele zilei",
            ["Admin.Configuration.Stores.Fields.DayIdError"] = "Ziu nevalidă",
            ["Admin.Configuration.Stores.Fields.Disable"] = "Dezactivați",
            ["Admin.Configuration.Stores.Fields.Enable"] = "Activați",
            ["Admin.Configuration.Stores.Fields.EnableDisableStore"] = "Magazin activat",
            ["Admin.Configuration.Stores.Fields.EndTime"] = "Ora de încheiere",
            ["Admin.Configuration.Stores.Fields.EndTime.hint"] = "Ora de încheiere",
            ["Admin.Configuration.Stores.Fields.EndTimeError"] = "Ora de încheiere nevalidă",
            ["Admin.Configuration.Stores.Fields.Friday"] = "Vineri",
            ["Admin.Configuration.Stores.Fields.Friday.hint"] = "Vineri",
            ["Admin.Configuration.Stores.Fields.HolidayName"] = "Numele vacanței",
            ["Admin.Configuration.Stores.Fields.HolidayName.hint"] = "Titlul vacanței",
            ["Admin.Configuration.Stores.Fields.LargeOrderEmailAddress"] = "Email address",
            ["Admin.Configuration.Stores.Fields.LargeOrderOrderAmount"] = "Order amount",
            ["Admin.Configuration.Stores.Fields.Monday"] = "Luni",
            ["Admin.Configuration.Stores.Fields.Monday.hint"] = "Luni",
            ["Admin.Configuration.Stores.Fields.PreOrderEmailAddress"] = "Email address",
            ["Admin.Configuration.Stores.Fields.PreOrderNotificationTime"] = "Notification time",
            ["Admin.Configuration.Stores.Fields.Saturday"] = "Sâmbătă",
            ["Admin.Configuration.Stores.Fields.Saturday.hint"] = "Sâmbătă",
            ["Admin.Configuration.Stores.Fields.StartTime"] = "Ora de începere",
            ["Admin.Configuration.Stores.Fields.StartTime.hint"] = "Ora de începere",
            ["Admin.Configuration.Stores.Fields.StoreCode"] = "Store Code",
            ["Admin.Configuration.Stores.Fields.StoreCode.Hint"] =
                "Unique store code (optional) to use in sales reports",
            ["Admin.Configuration.Stores.Fields.StorePickUp"] = "Ridicare din magazin",
            ["Admin.Configuration.Stores.Fields.Sunday"] = "Duminică",
            ["Admin.Configuration.Stores.Fields.Sunday.hint"] = "Duminică",
            ["Admin.Configuration.Stores.Fields.Thursday"] = "Joi",
            ["Admin.Configuration.Stores.Fields.Thursday.hint"] = "Joi",
            ["Admin.Configuration.Stores.Fields.Tuesday"] = "Marți",
            ["Admin.Configuration.Stores.Fields.Tuesday.hint"] = "Marți",
            ["Admin.Configuration.Stores.Fields.UniqueId"] = "Unique Id",
            ["Admin.Configuration.Stores.Fields.Wednesday"] = "Miercuri",
            ["Admin.Configuration.Stores.Fields.Wednesday.hint"] = "Miercuri",
            ["Admin.Configuration.Stores.ImportFromCsv"] = "Import stores from CSV",
            ["Admin.Configuration.Stores.OverlappingTimingConfigurations"] =
                "Modificările de configurare solicitate se suprapun cu orele curente ale magazinului pentru ziua selectată. Vă rugăm să remediați și să încercați din nou.",
            ["Admin.Configuration.Stores.ReasonLabel"] = "Select a reason:",
            ["Admin.Configuration.Tax"] = "Tax",
            ["Admin.Configuration.Tax.Mapping.Fields.AddNew"] = "Add new mapping",
            ["Admin.Configuration.Tax.Mapping.Fields.OrderType"] = "Order Type",
            ["Admin.Configuration.Tax.Mapping.Fields.Store"] = "Store",
            ["Admin.Configuration.Tax.Mapping.Fields.Store.All"] = "All stores",
            ["Admin.Configuration.Tax.Mapping.Fields.TaxCategories.All"] = "All tax categories",
            ["Admin.Configuration.Tax.Mapping.Fields.TaxCategory"] = "Tax Category",
            ["Admin.Configuration.Tax.TaxStoreOrderTypeMapping"] = "Tax mappings",
            ["Admin.GroupOrder.Fields.Status.Cancelled"] = "Anulat",
            ["Admin.GroupOrder.Fields.Status.Closed"] = "Finalizat",
            ["Admin.GroupOrder.Fields.Status.Open"] = "Deschis",
            ["Admin.GroupOrders.Fields.CreatedOn"] = "Creat pe",
            ["Admin.GroupOrders.Fields.Name"] = "Numele grupului",
            ["Admin.GroupOrders.Fields.OrderStatus"] = "Stare",
            ["Admin.GroupOrders.Fields.Owner"] = "Proprietar",
            ["Admin.GroupOrders.Fields.OwnerCustomerId"] = "Id client al proprietarului",
            ["Admin.GroupOrders.Fields.OwnerCustomerName"] = "Numele proprietarului",
            ["Admin.GroupOrders.Fields.UniqueIdentifier"] = "Identificator unic",
            ["Admin.Language.RunMigrations"] = "Run Migrations",
            ["Admin.Language.RunMigrations.Failure"] = "Migrations could not run, error message: ",
            ["Admin.Language.RunMigrations.Success"] = "Migrations run successfully.",
            ["Admin.Orders.Fields.OrderType"] = "Tip de comandă",
            ["Admin.Promotions.Discounts.Fields.CouponCode.Required"] = "Vă rugăm să furnizați un cod de cupon",
            ["Admin.Reports.StoreStatus"] = "Store Status",
            ["Admin.Reports.StoreStatus.EndDate"] = "End Date",
            ["Admin.Reports.StoreStatus.Fields.Comment"] = "Comment",
            ["Admin.Reports.StoreStatus.Fields.Date"] = "Date",
            ["Admin.Reports.StoreStatus.Fields.Reason"] = "Reason",
            ["Admin.Reports.StoreStatus.Fields.Status"] = "Store Status",
            ["Admin.Reports.StoreStatus.Fields.StoreId"] = "Store Id",
            ["Admin.Reports.StoreStatus.Fields.StoreName"] = "Store Name",
            ["Admin.Reports.StoreStatus.RunReport"] = "Run Report",
            ["Admin.Reports.StoreStatus.StartDate"] = "Start Date",
            ["Admin.Reports.StoreStatus.Status"] = "Store Status",
            ["Admin.Reports.StoreStatus.Store"] = "Store",
            ["Admin.Stores.Stores.List.SearchName"] = "Name",
            ["Admin.Stores.Stores.List.SearchName"] = "Store Name",
            ["Admin.Stores.Stores.List.SearchStoreStatus"] = "Status",
            ["Admin.Stores.Stores.List.SearchUniqueId"] = "Unique Id",
            ["BridgeTerm.carbohydratesGrams.Title"] = "Carbohidrați",
            ["BridgeTerm.carbohydratesGrams.Unit"] = "g",
            ["BridgeTerm.chlorineMilligrams.Title"] = "Clor",
            ["BridgeTerm.chlorineMilligrams.Unit"] = "mg",
            ["BridgeTerm.energykCal.Title"] = "Energie",
            ["BridgeTerm.energykCal.Unit"] = "kCal",
            ["BridgeTerm.fatGrams.Title"] = "Grăsime",
            ["BridgeTerm.fatGrams.Unit"] = "g",
            ["BridgeTerm.healthRating.Title"] = "Evaluare de sănătate",
            ["BridgeTerm.healthRating.Unit"] = " ",
            ["BridgeTerm.hydrogenCarbonateMilligrams.Title"] = "Hydrogen Carbonate",
            ["BridgeTerm.hydrogenCarbonateMilligrams.Unit"] = "mg",
            ["BridgeTerm.magnesiumMilligrams.Title"] = "Magneziu",
            ["BridgeTerm.magnesiumMilligrams.Unit"] = "mg",
            ["BridgeTerm.nitratesMilligrams.Title"] = "Nitrați",
            ["BridgeTerm.nitratesMilligrams.Unit"] = "mg",
            ["BridgeTerm.phValue.Title"] = "Valoare PH",
            ["BridgeTerm.phValue.Unit"] = " ",
            ["BridgeTerm.potassiumMilligrams.Title"] = "Potasiu",
            ["BridgeTerm.potassiumMilligrams.Unit"] = "mg",
            ["BridgeTerm.proteinGrams.Title"] = "Proteine",
            ["BridgeTerm.proteinGrams.Unit"] = "g",
            ["BridgeTerm.saltGrams.Title"] = "Sare",
            ["BridgeTerm.saltGrams.Unit"] = "g",
            ["BridgeTerm.saturatedFatGrams.Title"] = "Grăsimi saturate",
            ["BridgeTerm.saturatedFatGrams.Unit"] = "g",
            ["BridgeTerm.sodiumMilligrams.Title"] = "Sodiu",
            ["BridgeTerm.sodiumMilligrams.Unit"] = "mg",
            ["BridgeTerm.sodiumGrams.Title"] = "Sodiu",
            ["BridgeTerm.sodiumGrams.Unit"] = "g",
            ["BridgeTerm.sugarGrams.Title"] = "Zahăr",
            ["BridgeTerm.sugarGrams.Unit"] = "g",
            ["BridgeTerm.sulfatesMilligrams.Title"] = "Sulfați",
            ["BridgeTerm.sulfatesMilligrams.Unit"] = "mg",
            ["BridgeTerm.fibreGrams.Title"] = "Fibre",
            ["BridgeTerm.fibreGrams.Unit"] = " g",
            ["Checkorder.ProblematicMappings.Error"] = "There's a problem with the items in your cart.",
            ["Checkout.BackToMenu"] = "Înapoi la meniu",
            ["Checkout.BackToMenu"] = "Înapoi",
            ["Checkout.CouldNotPlaceOrder"] = "Nu am putut plasa comanda",
            ["Checkout.CustomerCheckout"] = "Încheierea clientului",
            ["Checkout.CustomerCheckout.ReviewYourOrder"] = "Review your order",
            ["Checkout.CustomerInformation.Curbside.Details"] = "Detaliile dvs.",
            ["Checkout.CustomerInformation.Curbside.Vehicle"] = "Detaliile vehiculului dvs.",
            ["Checkout.CustomerInformation.Vehicle.Colour"] = "Culoare",
            ["Checkout.CustomerInformation.Vehicle.Model"] = "Model/Marcă",
            ["Checkout.CustomerInformation.Vehicle.Plate"] = "Placă de înmatriculare",
            ["Checkout.CustomertInformation.Address1"] = "Adresa stradală 1",
            ["Checkout.CustomertInformation.Address2"] = "Adresa stradă 2",
            ["Checkout.CustomertInformation.City"] = "Oraș",
            ["Checkout.CustomertInformation.Country"] = "Selectați țara",
            ["Checkout.CustomertInformation.County"] = "Județ",
            ["Checkout.CustomertInformation.DeliveryInstructions"] = "Instrucțiuni de livrare",
            ["Checkout.CustomertInformation.Email"] = "E-mail",
            ["Checkout.CustomertInformation.FaxNumber"] = "Fax",
            ["Checkout.CustomertInformation.FirstName"] = "Prenumele",
            ["Checkout.CustomertInformation.Iagreetothe"] = "Sunt de acord cu",
            ["Checkout.CustomertInformation.LastName"] = "Nume",
            ["Checkout.CustomertInformation.OrderNotes"] = "Note de comandă",
            ["Checkout.CustomertInformation.PhoneNumber"] = "Telefon",
            ["Checkout.CustomertInformation.SaveAddress"] = "Save this address in my addresses list",
            ["Checkout.CustomertInformation.SaveVehicle"] = "Save this vehicle in my vehicles list",
            ["Checkout.CustomertInformation.StateProvince"] = "Selectați starea",
            ["Checkout.CustomertInformation.TermsAndCondition"] = "Termeni și condiții",
            ["Checkout.CustomertInformation.ZipPostalCode"] = "Cod poștal",
            ["Checkout.EnterCVV.Wait"] = "Please enter the CV2 for this card",
            ["Checkout.GuestCheckout"] = "Casa invitat",
            ["Checkout.GuestCheckout.ReviewYourOrder"] = "Review your order",
            ["Checkout.Interested.Title"] = "Pe baza selecției dvs., ați putea fi interesat de următoarele articole",
            ["Checkout.MarketingEmails"] = "Primiți e-mailurile noastre de marketing și oferte",
            ["Checkout.MarketingEmailsOptOut"] = "Do not receive our marketing and offer emails",
            ["Checkout.MarketingEmailsOptOut"] = "Nu primiți e-mailurile noastre de marketing și oferte",
            ["Checkout.Oops.Button.BackToMenu"] = "ÎNAPOI LA MENIU",
            ["Checkout.Oops.Button.TryAgain"] = "ÎNCERCAȚI DIN NOU",
            ["Checkout.Oops.ItemsHaveBeenSave"] = "Nu vă faceți griji, articolele dvs. au fost salvate.",
            ["Checkout.Oops.Title"] = "Hopa!",
            ["Checkout.Oops.UnableToProcess"] =
                "Din păcate, nu am putut procesa plata dvs. Vă rugăm să vă asigurați că aveți suficiente fonduri sau să încercați un alt card.",
            ["Checkout.OrderDetails.Button.Finish"] = "Finalizare",
            ["Checkout.OrderDetails.Button.SaveReceipt"] = "SALVAȚI CHITANTA",
            ["Checkout.OrderDetails.Button.StartNewOrder"] = "ÎNCEPEȚI O COMANDĂ NOUĂ",
            ["Checkout.OrderDetails.Collection.Address"] = "Adresa de colectare",
            ["Checkout.OrderDetails.Collection.Time"] = "Ora de colectare",
            ["Checkout.OrderDetails.Curbside.Address"] = "Adresa de colectare",
            ["Checkout.OrderDetails.Curbside.Time"] = "Ora de colectare",
            ["Checkout.OrderDetails.Delivery.Address"] = "Adresa de livrare",
            ["Checkout.OrderDetails.DineIn.WeRecommendYouArrive"] =
                "Ne propunem să vă aducem comanda la masa dvs. în zece minute",
            ["Checkout.OrderDetails.Title"] = "Vești bune!",
            ["Checkout.OrderDetails.Title.FiveguysUK"] = "Mulțumesc",
            ["Checkout.OrderDetails.Title.FiveguysDE"] = "Mulțumesc",
            ["Checkout.OrderDetails.Title.chikn"] = "Mulțumesc",
            ["Checkout.OrderDetails.WeRecommendYouArrive"] =
                "Vă recomandăm să ajungeți nu mai devreme sau mai târziu de 5 minute pentru a vă ridica comanda, acest lucru vă va asigura că mâncarea este proaspăt pregătită la colectare.",
            ["Checkout.OrderDetails.YourOrderHasBeenAccepted"] =
                "Comanda dvs. a fost acceptată și veți primi un e-mail de confirmare în curând.",
            ["Checkout.OrderSummary.Change"] = "Schimbare",
            ["Checkout.OrderSummary.Title"] = "Rezumatul comenzii",
            ["Checkout.OrderSummary.Total"] = "Total",
            ["Checkout.Payment.CouldNotCompleteCaptureInTime"] =
                "Captarea acestei plăți a durat mai mult de 20 de minute, așa că am expirat această comandă.",
            ["Checkout.Payment.CouldNotCompleteCaptureInTimeAuthorized"] =
                "Captarea acestei plăți a durat mai mult de 20 de minute, așa că am expirat această comandă, aceasta poate fi o situație extraordinară din partea furnizorului dvs. de plăți, vă rugăm să verificați dacă este necesară rambursarea și să ne contactați dacă da, cu referința: ",
            ["Checkout.Payment.PartiallyRefundedBeforeConfirmation"] = "Comanda dvs. a fost rambursată parțial.",
            ["Checkout.Payment.RefundedBeforeConfirmation"] = "Comanda dvs. a fost rambursată.",
            ["Checkout.Payment.VoidedBeforeConfirmation"] = "Comanda dvs. a fost anulată.",
            ["Checkout.PaymentButton.ProceedToPaymentOptions"] = "PROCEDAȚI LA OPȚIUNILE DE PLATĂ",
            ["Checkout.PaymentButton.ProceedToPaymentOptions.FiveguysUK"] = "PROCEDAȚI CU PLATA",
            ["Checkout.PaymentButton.ProceedToPaymentOptions.FiveguysDE"] = "PROCEDAȚI CU PLATA",
            ["Checkout.PaymentInfo.Button"] = "PROCEDAȚI CU PLATA",
            ["Checkout.PaymentMethod.BacktoMenu"] = "Înapoi",
            ["Checkout.PaymentMethod.Button.DigitalWallet"] = "Portofel digital",
            ["Checkout.PaymentMethod.Button.PayUsingDigitalWallet"] = "Plătiți folosind portofelul digital",
            ["Checkout.PaymentMethod.Button.PayWithCard"] = "Plătiți cu cardul",
            ["Checkout.PaymentMethod.Popup.PayWithDigital"] = "Plătiți folosind portofelul digital",
            ["Checkout.PaymentMethod.Popup.Title"] = "Cum ați dori să plătiți?",
            ["Checkout.PaymentMethod.Popup.Title.PaymentMethod"] = "METODA DE PLATA",
            ["Checkout.PaymentMethod.WalletDisclaimer"] =
                "* Apple Pay este disponibil numai în Safari.Google Pay este disponibil numai în Chrome",
            ["Checkout.Please.Wait"] = "Processing your request, please wait ...",
            ["Checkout.PrivacyPolicy"] = "politica de confidențialitate",
            ["Checkout.PrivacyPolicy.Note"] =
                "Folosim informațiile pe care ni le oferiți aici pentru a vă procesa comanda. Pentru a afla mai multe informații despre cum și de ce folosim informațiile vă rugăm să consultați politica noastră de confidențialitate",
            ["Checkout.PrivacyPolicy.Note.Partial"] =
                "Folosim informațiile pe care ni le furnizați aici pentru a procesa comanda dvs. Pentru a afla mai multe informații despre cum și de ce folosim informațiile, vă rugăm să consultați ",
            ["Checkout.ProcessingOrder.message"] = "Procesarea comenzii",
            ["Checkout.ProcessingOrder.message.FiveguysUK"] = "PROCESARE PLATA...",
            ["Checkout.ProcessingOrder.message.FiveguysDE"] = "PROCESARE PLATA...",
            ["Checkout.Recaptcha.Error"] = "Recaptcha trebuie finalizat mai întâi.",
            ["Checkout.RemoveAllItem.ClearOrder"] = "ȘTERGEȚI COMANDA",
            ["Checkout.RemoveAllItem.Confirmation.Continue"] = "CONTINUA",
            ["Checkout.RemoveAllItem.Confirmation.Continue.FiveguysUK"] = "DA",
            ["Checkout.RemoveAllItem.Confirmation.Continue.FiveguysDE"] = "DA",
            ["Checkout.RemoveAllItem.Confirmation.GoBack"] = "ÎNAPOI",
            ["Checkout.RemoveAllItem.Confirmation.GoBack.FiveguysUK"] = "NU",
            ["Checkout.RemoveAllItem.Confirmation.GoBack.FiveguysDE"] = "NU",
            ["Checkout.RemoveAllItem.Confirmation.Message"] =
                "Acest lucru va elimina toate articolele din comanda dvs.",
            ["Checkout.RemoveAllItem.Confirmation.Message.FiveguysUK"] = "Eliminați toate articolele din comandă?",
            ["Checkout.RemoveAllItem.Confirmation.Message.FiveguysDE"] = "Eliminați toate articolele din comandă?",
            ["Checkout.RemoveItem.Confirmation.Message"] = "Sunteți sigur că doriți să eliminați acest articol?",
            ["Checkout.RemoveItem.Confirmation.No"] = "Nu",
            ["Checkout.RemoveItem.Confirmation.Yes"] = "Da",
            ["Checkout.SomethingWentWrong"] = "Ceva a mers prost când încercați să procesați comanda dvs.",
            ["Checkout.Subtitle"] = "Introduceți detaliile dvs. mai jos sau",
            ["Checkout.SubtitleShort"] = "Introduceți detaliile dvs",
            ["Checkout.Subtitle.LoginRegister"] = "autentificare / înregistrare",
            ["Common.AddAddress"] = "Adăugați adresa",
            ["Common.EditAddress"] = "Editați adresa",
            ["Common.Product.BackToMenu"] = "Înapoi la meniu",
            ["Common.Product.BackToMenu.FiveguysUK"] = "Înapoi",
            ["Common.Product.BackToMenu.FiveguysDE"] = "Înapoi",
            ["Curbside.Vehicle"] = "VEHICUL",
            ["Curbside.Vehicle.PlateIsRequired"] = "Este necesară plăcuța de înmatriculare.",
            ["Curbside.Vehicle.VehicleModelIsRequired"] = "Este necesar modelul vehiculului.",
            ["Curbside.maintitle"] = "Când doriți să vă colectați",
            ["Curbside.note"] =
                "Notă: vi se va cere să parcați într-o zonă desemnată. Intervalele orare se pot modifica în timpul procesului de comandă, intervalul orar real va fi confirmat în timpul plății.",
            ["Curbside.searchtitle"] = "Ridicare de la bord",
            ["Curbside.subtitle"] = "comanda?",
            ["Curbside.updatemaintitle"] = "VĂ rugăm SELECTAȚI UN NOU",
            ["Curbside.updatesearchtitle"] =
                "Intervalul dvs. orar anterior nu mai este disponibil <br/> coșul dvs. rămâne salvat",
            ["Curbside.updatesubtitle"] = "Timp de ridicare din bordura",
            ["Default.Continue"] = "Continue",
            ["Default.Default"] = "Default",
            ["Default.Ok"] = "OK",
            ["Delivery.maintitle"] = "CÂND ȚI VĂ PLACE",
            ["Delivery.note"] =
                "Notă: timpul de livrare disponibil se poate modifica în timpul procesului de comandă, intervalul de livrare real va fi confirmat în timpul plății.",
            ["Delivery.searchtitle"] = "Livrare de la",
            ["Delivery.subtitle"] = "COMANDA LIVRATA?",
            ["Delivery.updatemaintitle"] = "VĂ rugăm SELECTAȚI UN NOU",
            ["Delivery.updatesearchtitle"] =
                "Intervalul dvs. orar anterior nu mai este disponibil <br/> coșul dvs. rămâne salvat",
            ["Delivery.updatesubtitle"] = "TIMP DE LIVRARE",
            ["DineIn.Subtitle.Unavailable"] = "Ne pare rău, dar masa nu este disponibilă pentru acest magazin",
            ["DineIn.TableAt"] = " la masa ",
            ["DineIn.Title"] = "Luați masa la",
            ["DineIn.placeholder.tablenumber"] = "Introduceți numărul tabelului",
            ["DineIn.startorder"] = "Începe comanda",
            ["DineIn.subtitle"] = "Serviciul de masă la:",
            ["FiveGuys.Footer.AllergenInfo"] = "Allergen Info",
            ["FiveGuys.Footer.Contact"] = "Contact",
            ["FiveGuys.Footer.FAQs"] = "FAQs",
            ["FiveGuys.Footer.Ingredients"] = "Ingredients",
            ["FiveGuys.Footer.Legal"] = "Legal",
            ["FiveGuys.Footer.NutritionalInfo"] = "Nutritional Info",
            ["FiveGuys.Footer.PrivacyPolicy"] = "Privacy Policy",
            ["FiveGuys.Footer.TermsConditions"] = "Terms &amp; Conditions",
            ["FiveGuys.Header.AboutUs"] = "Despre noi",
            ["FiveGuys.Header.GiftCards"] = "Carduri cadou",
            ["FiveGuys.Header.Jobs"] = "Muncă",
            ["FiveGuys.Header.Location"] = "Locație",
            ["FiveGuys.Header.Menu"] = "Meniul",
            ["FiveGuys.Header.Merch"] = "Merch",
            ["Footer.PoweredByLineten"] = "Cu sprijinul Lineten",
            ["GroupOrdering.Cancel"] = "Cancel",
            ["GroupOrdering.CompleteMyOrder"] = "Complete my order",
            ["GroupOrdering.ContinueToCheckout"] = "Continue to checkout",
            ["GroupOrdering.CreateGroup"] = "Create Group",
            ["GroupOrdering.CreateGroup.InviteYourGuests"] = "Invite your guests by sharing the link below",
            ["GroupOrdering.CreateGroup.ProceedToMenu"] = "Proceed To Menu",
            ["GroupOrdering.CreateGroup.Share"] = "Share",
            ["GroupOrdering.CreateGroup.Success"] = "Your group order has been created",
            ["GroupOrdering.CreateGroupOrder"] = "Creează o comandă de grup",
            ["GroupOrdering.CreateGroupOrder.Mobile"] = "comandă de grup",
            ["GroupOrdering.CreateGroupOrder.Subtitle"] =
                "Creați-vă grupul și invitați oaspeții să-și adauge comanda în coș!",
            ["GroupOrdering.DeleteGroupOrder"] = "Cancel Group Order",
            ["GroupOrdering.Finish"] = "Finish",
            ["GroupOrdering.Finished"] = "Finished",
            ["GroupOrdering.GoBack"] = "Go back",
            ["GroupOrdering.GroupName"] = "Name your Group",
            ["GroupOrdering.GroupNameError"] = "Group name is required",
            ["GroupOrdering.Guests"] = "Guests",
            ["GroupOrdering.Invitation"] = "Hello, you have been invited to join a group order",
            ["GroupOrdering.IsEveryoneReady"] = "Is Everyone Ready?",
            ["GroupOrdering.IsEveryoneReady.Subtitle"] =
                "It looks like one or more guests have not finished. <br/><br/> If you proceed to checkout, the group order will be locked for your guests and they will no longer be able to edit their items.",
            ["GroupOrdering.Item"] = " item",
            ["GroupOrdering.Items"] = " items",
            ["GroupOrdering.ItemsAdded"] = "Your items have been added to the groups final order",
            ["GroupOrdering.JoinGroup.Details"] =
                "You can add items to this order and eveything will be collected together.",
            ["GroupOrdering.JoinGroup.EnterYourName"] = "Enter your name and join the group",
            ["GroupOrdering.JoinGroup.HostIsPaying"] = ":: The host is paying for this order ::",
            ["GroupOrdering.JoinGroup.Join"] = "Join ",
            ["GroupOrdering.JoinGroup.JoinOrder"] = "Join order",
            ["GroupOrdering.JoinGroup.Order"] = " order?",
            ["GroupOrdering.KeepGuest"] = "Keep Guest",
            ["GroupOrdering.LeaveGroup.Subtitle"] = "You and your items will be removed from the group.",
            ["GroupOrdering.LeaveGroupOrder"] = "Leave Group",
            ["GroupOrdering.Owner"] = "Owner",
            ["GroupOrdering.ReadyToFinish"] = "Ready to Finish?",
            ["GroupOrdering.ReadyToFinish.Subtitle"] =
                "If you proceed, you will no longer be able to edit your items and will have to contact the group owner to make any changes.",
            ["GroupOrdering.RemoveGuest"] = "Remove Guest",
            ["GroupOrdering.RemoveGuest.AreYouSure"] = "Remove guest from the Group Order?",
            ["GroupOrdering.RemoveGuest.Subtitle"] =
                "This Guest and any items that they have added will be removed from your group order.",
            ["GroupOrdering.StayInGroup"] = "Stay in group",
            ["GroupOrdering.SubTotal"] = " Sub total: ",
            ["GroupOrdering.Timeslot.Notes"] =
                "Note: Time slots may change slightly during the ordering process. Your collection slot will be confirmed during checkout.",
            ["GroupOrdering.Timeslot.Unavailable"] =
                "To help us prepare your group order, we have adjusted your collection time.",
            ["GroupOrdering.You"] = "You",
            ["GroupOrdering.YouHaveLeft"] = "You left the group order",
            ["JourneyRestart.SessionExpired"] = "Your session expired",
            ["KitchenCapacity.SelectSlots"] = "Selectați slotul",
            ["Menu.OnlineOrder"] = "Comanda",
            ["Menu.Ordersummary.Checkout"] = "CHECKOUT",
            ["Menu.Ordersummary.ClearAll"] = "ȘTERGEȚI COMANDA",
            ["Menu.Ordersummary.Collection.Change"] = "Schimbare",
            ["Menu.Ordersummary.Collection.Collection"] = "Colectați de la",
            ["Menu.Ordersummary.Collection.Curbside"] = "Ridicare din bordură",
            ["Menu.Ordersummary.Collection.Delivery"] = "Livrare de la",
            ["Menu.Ordersummary.Collection.DineIn"] = "Luați masa la",
            ["Menu.Ordersummary.Collection.TimeAt"] = "la",
            ["Menu.Ordersummary.Collection.TimeFrom"] = "de la",
            ["Menu.Ordersummary.Collection.TimeTo"] = "la",
            ["Menu.Ordersummary.EmptyOrder"] =
                "Comanda dvs. este goală, faceți clic pe un articol pentru a-l adăuga la comanda dvs.",
            ["Menu.Ordersummary.GroupOrder.Mobile.Checkout"] = "Review my items",
            ["Menu.Ordersummary.GroupOrder.OrderTotal"] = "Group Order Total: ",
            ["Menu.Ordersummary.InvertedCheckbox.Prefix"] = "NO",
            ["Menu.Ordersummary.Modalpopup.ClearAllItem.Back"] = "ÎNAPOI",
            ["Menu.Ordersummary.Modalpopup.ClearAllItem.Continue"] = "CONTINUA",
            ["Menu.Ordersummary.Modalpopup.ClearAllItem.Text"] =
                "Acest lucru va elimina toate articolele<br/>din comanda ta",
            ["Menu.Ordersummary.Modalpopup.ClearAllItem.Text.FiveguysUK"] =
                "Acest lucru va elimina<br/>toate articolele<br/>din comanda ta",
            ["Menu.Ordersummary.Modalpopup.ClearAllItem.Text.FiveguysDE"] =
                "Acest lucru va elimina<br/>toate articolele<br/>din comanda ta",
            ["Menu.Ordersummary.Modalpopup.RemoveItem.No"] = "Nu",
            ["Menu.Ordersummary.Modalpopup.RemoveItem.Text1"] = "Sunteți sigur că doriți",
            ["Menu.Ordersummary.Modalpopup.RemoveItem.Text2"] = "eliminați acest articol?",
            ["Menu.Ordersummary.Modalpopup.RemoveItem.Yes"] = "Da",
            ["Menu.Ordersummary.ReviewOrder"] = "REvizualizați COMANDA",
            ["Menu.Ordersummary.ReviewYourOrder"] = "EXAMINĂ-ȚI COMANDA",
            ["Menu.Ordersummary.Title"] = "Rezumatul comenzii",
            ["Menu.Ordersummary.Total"] = "Total",
            ["Menu.Ordersummary.back"] = "Înapoi",
            ["Menu.AllergensModal.Title"] = "O notă pentru oaspeții noștri cu alergii",
            ["Menu.AllergensModal.SubTitle"] =
                "Din păcate, nu putem accepta comenzi de alergii online sau prin telefon",
            ["Menu.AllergensModal.FirstParagraph"] =
                "Această decizie asigură siguranța oaspeților noștri cu alergii, dacă doriți să plasați o comandă pentru alergii, vă rugăm să vizitați unul dintre restaurantele noastre + să plasați comanda unui membru al echipei.",
            ["Menu.AllergensModal.SecondParagraph"] = "",
            ["Menu.AllergensModal.ContinueButton"] = "Continuați comanda",
            ["Menu.AllergensModal.ViewGuidelinesButton"] = "Vizualizați instrucțiunile",
            ["Order.Allergies.Notes.FiveguysUK"] =
                "We’re sorry but we are unable to cater for allergies of food intolerances placed online, only instore orders. For health and safety reasons, if you suffer from a peanut allergy please do not order a milkshake of fries. If you require any information regarding allergens in food, please refer to the allergen and ingredients guides in the links below.",
            ["Order.Allergies.Notes.FiveguysDE"] =
                "We’re sorry but we are unable to cater for allergies of food intolerances placed online, only instore orders. For health and safety reasons, if you suffer from a peanut allergy please do not order a milkshake of fries. If you require any information regarding allergens in food, please refer to the allergen and ingredients guides in the links below.",
            ["Order.Minimumorder"] = "Comanda minima",
            ["Order.OrderAgain"] = "Comandați din nou",
            ["Order.OrderConfirmation.AddressTextCollection"] = "Adresa de colectare: ",
            ["Order.OrderConfirmation.AddressTextDelivery"] = "Adresa de livrare: ",
            ["Order.OrderDetails"] = "DETALII COMANDĂ",
            ["Order.OrderTotal"] = "Total",
            ["Order.Type.Notes.FiveguysUK"] =
                "<p><strong>Curbside:</strong> For curbside order you will be asked to park in a designated area. Please refer to your order confirmation for details. </p> <p><strong>Collect+:</strong> We prep when you are nearby</p>",
            ["Order.Type.Notes.FiveguysDE"] =
                "<p><strong>Curbside:</strong> For curbside order you will be asked to park in a designated area. Please refer to your order confirmation for details. </p> <p><strong>Collect+:</strong> We prep when you are nearby</p>",
            ["POSBridge.SubmitFail.PlaceOrder.RefundFailed"] =
                "Din păcate, din cauza unor probleme tehnice, magazinul nu o poate primi. <br/> Nu am putut rambursa comanda dvs., vă rugăm să ne contactați.",
            ["POSBridge.SubmitFail.PlaceOrder.RefundSucceed"] =
                "Din păcate, din cauza unor probleme tehnice, magazinul nu o poate primi. <br/> Comanda dvs. a fost rambursată cu succes.",
            ["PageTitle.GroupOrdering.JoinGroup"] = "Join Group Order",
            ["Payment.ProcessingOrder.Timeout"] =
                "Your payment was successful but we are unable to confirm the order with the store, please contact the store directly to check if a refund is necessary: ",
            ["PaymentMethod.OngoingOrder.Back"] = "You did not complete your payment successfully",
            ["Product.AllergensAndIngredients"] = "Alergeni și informații nutriționale",
            ["Product.AllergensAndIngredients.Allergens.Subtitle"] = "Produsul conține următorii alergeni",
            ["Product.AllergensAndIngredients.ModalAllergensTab"] = "Alergeni",
            ["Product.AllergensAndIngredients.ModalIngredientsTab"] = "Ingrediente",
            ["Product.AllergensAndIngredients.ModalNutritionTab"] = "Nutriție",
            ["Product.AllergensAndIngredients.ModalTitle"] = "Informații despre nutriție și alergeni",
            ["Product.AllergensAndIngredients.ModalTitle.FiveguysUK"] = "Nutrition & Allergens",
            ["Product.AllergensAndIngredients.ModalTitle.FiveguysDE"] = "Nutrition & Allergens",
            ["Product.AllergensAndIngredients.Nutrition.SubtitleLeft"] = "Valori tipice",
            ["Product.AllergensAndIngredients.Nutrition.SubtitleRight"] = "Per 100g",
            ["Product.Attributes.Max.Selection.Not.Met"] = "Too many attribute values selected",
            ["Product.Attributes.Min.Selection.Not.Met"] = "Too few attribute values selected",
            ["Products.LimitedTimeAvailability.Product"] = "Disponibilitate în timp limitat*",
            ["Products.LimitedTimeAvailability.Product.OutOfStock"] = "Epuizat",
            ["Products.RelatedProductsNxg"] = "De asemenea, s-ar putea să vă placă...",
            ["Products.ProductInfo"] = "Informatiile produsului",
            ["Punchh.SeeYourRewards"] = "Vedeți recompensele",
            ["ReOrder.Error.ReservationNotFound"] =
                "Nu am putut alege magazinul pentru această comandă, dar articolele au fost adăugate în coșul dvs., utilizați butonul „Încercați din nou” pentru a alege magazinul și continuați cu această comandă",
            ["Reviews.Overview.LoginToReview"] = "Autentificați-vă pentru a evalua acest produs",
            ["Reviews.Write.CustomNXG"] = "Revizuire pentru",
            ["Settings.UserJourneySettings.Edit"] = "User journey settings were edited.",
            ["ShoppingCart.AddToCart.Cancel"] = "Anulați",
            ["ShoppingCart.AddToCart.FiveguysUK"] = "Adăugați pentru ",
            ["ShoppingCart.AddToCart.FiveguysDE"] = "Adăugați pentru ",
            ["ShoppingCart.AlterQuantity.FiveguysUK"] = "Vrei mai mult de 1?",
            ["ShoppingCart.AlterQuantity.FiveguysDE"] = "Vrei mai mult de 1?",
            ["ShoppingCart.CrossSells.FiveguysUK"] =
                "Ne-am gândit că ați putea fi interesat și de următoarele articole:",
            ["ShoppingCart.CrossSells.FiveguysDE"] =
                "Ne-am gândit că ați putea fi interesat și de următoarele articole:",
            ["ShoppingCart.HaveADiscountCode"] = "Ai un cod de reducere?",
            ["ShoppingCart.Totals.DeliveryFees"] = "Taxa de livrare",
            ["Store.SelectDays"] = "Selectați ziua",
            ["Store.Today"] = "Astăzi",
            ["Tacobell.Footer.AboutUs"] = "Despre noi",
            ["Tacobell.Footer.AllergenInfo"] = "Informații despre alergen",
            ["Tacobell.Footer.AppTerms"] = "Termeni și condiții",
            ["Tacobell.Footer.CookiesPolicy"] = "Declarația cookie",
            ["Tacobell.Footer.CustomerServices"] = "Contact",
            ["Tacobell.Footer.LatestNews"] = "Ultimele știri",
            ["Tacobell.Footer.Locations"] = "Locații",
            ["Tacobell.Footer.MailingList"] = "Lista de corespondență",
            ["Tacobell.Footer.Menu"] = "Meniu",
            ["Tacobell.Footer.NutritionInformation"] = "Nutrition Information",
            ["Tacobell.Footer.PrivacyPolicy"] = "Politică de confidențialitate",
            ["Tacobell.Footer.Registered"] = "Taco Bell înregistrat în 2021",
            ["Tacobell.Footer.ResponsibleDisclosure"] = "Dezvăluirea responsabilă",
            ["Tacobell.Footer.SiteMap"] = "Harta site-ului",
            ["Tacobell.Footer.WebsiteTerms"] = "Termenii site-ului",
            ["Tacobell.Footer.WifiPolicy"] = "Politica Wi-Fi Taco Bell",
            ["Tacobell.Header.ContactUs"] = "Contactați-ne",
            ["Tacobell.Header.Locations"] = "Locații",
            ["Tacobell.Header.Menu"] = "Meniu",
            ["Tacobell.Login"] = "Autentificare/Înregistrare",
            ["Tacobell.Logout"] = "Deconectare",
            ["Wagamama.Header.Menu"] = "Meniul",
            ["Wagamama.Header.Order"] = "Ordin",
            ["Wagamama.Header.Restaurant"] = "Restaurant",
            ["Wagamama.Header.Restaurants"] = "Restaurante",
            ["Wagamama.Header.Cook"] = "Bucătar",
            ["Wagamama.Header.Shop"] = "Magazin",
            ["Wagamama.Header.WagamamaWay"] = "Wagamama mod",
            ["Wagamama.Header.Gifting"] = "Cadouri",
            ["UserJourney.NoToppingsModalEnabled.Body"] = "Just checking that you definitely don't want any toppings.",
            ["UserJourney.NoToppingsModalEnabled.ButtonAddToppings"] = "Add toppings",
            ["UserJourney.NoToppingsModalEnabled.ButtonDontAddToppings"] = "Don't add toppings",
            ["UserJourney.NoToppingsModalEnabled.Title"] = "No Toppings?",
            ["Vehicle.Colour"] = "Colour*",
            ["Vehicle.RegistrationPlate"] = "Registration number*",
            ["admin.catalog.kitchencapacity.storetimings.backtokitchen"] = "Înapoi la capacitatea bucătăriei",
            ["admin.catalog.kitchencapacity.timings.alert.slotreservation"] =
                "Vă rugăm să introduceți rezervarea în magazin mai mare sau egală cu capacitatea slotului",
            ["admin.catalog.mgs.addnew"] = "Add new modifier group selector",
            ["admin.catalog.products.productattributeordertypemapping.hint"] =
                "Specify for what type of order (and optionally store) this product attribute is available in",
            ["admin.catalog.products.productattributes.attributes.editstoretimingsdetails"] =
                "Editați detaliile orelor magazinului",
            ["admin.catalog.products.productordertypemapping.savebeforeedit"] =
                "You need to save the product before you can add new order type mappings.",
            ["admin.catalog.store.dayselect.savebeforeedit"] =
                "Trebuie să salvați magazinul înainte de a putea adăuga zile pentru această pagină de magazin.",
            ["admin.catalog.store.holiday.addnew"] = "Adăugați o nouă vacanță",
            ["admin.catalog.store.holiday.exportcsv"] = "Exportă ca CSV",
            ["admin.catalog.store.holiday.importcsv"] = "Importă din CSV",
            ["admin.catalog.store.holiday.ExportAllSeasonalCsv"] = "Exportă orele de deschidere sezoniere ca CSV",
            ["admin.catalog.store.holiday.ImportAllSeasonalCsv"] = "Importă orele de deschidere sezoniere din CSV",
            ["admin.catalog.store.holiday.alert.addnew"] = "Vă rugăm să furnizați numele și data sărbătorii.",
            ["admin.catalog.store.holiday.fields.DateError"] = "Data nevalidă",
            ["admin.catalog.store.holiday.fields.date"] = "Data",
            ["admin.catalog.store.holiday.fields.starttime"] = "Timpul de începere",
            ["admin.catalog.store.holiday.fields.endtime"] = "Sfârșitul timpului",
            ["admin.catalog.store.holiday.fields.holidayname"] = "Numele Sărbătorii",
            ["admin.catalog.store.holiday.fields.holidaynameerror"] = "Vă rugăm să alegeți un nume de vacanță valid",
            ["admin.catalog.store.pickupform.savebeforeedit"] =
                "Trebuie să salvați magazinul înainte de a putea adăuga ridicare pentru această pagină de magazin.",
            ["admin.catalog.store.storeholiday.addbutton"] = "Adăugați vacanță",
            ["admin.catalog.store.storeholiday.backtostore"] = "înapoi la magazin",
            ["admin.catalog.store.storeholiday.editstoreholidaydetails"] = "Editați detaliile sărbătorilor din magazin",
            ["admin.catalog.store.storetimings.addbutton"] = "Adăugați Timing",
            ["admin.catalog.store.storetimings.backtostore"] = "înapoi la magazin",
            ["admin.catalog.store.timings.addnew"] = "Adăugați orare noi",
            ["admin.catalog.store.timings.alert.addnew"] = "Toate campurile sunt necesare.",
            ["admin.catalog.store.timings.fields.StartTimeError"] = "Ora de începere nevalidă",
            ["admin.catalog.store.timings.fields.endtime"] = "Sfârșitul timpului",
            ["admin.catalog.store.timings.fields.starttime"] = "Timpul de începere",
            ["admin.catalog.store.workday.selectbeforeedit"] = "Vă rugăm să selectați mai întâi zilele de deschidere",
            ["admin.common.configure"] = "Configurarea magazinului",
            ["admin.configuration.Spa.timings.selectday"] = "Selectați zile",
            ["admin.configuration.catalog.menupublish"] = "Statutul publicării meniului",
            ["Admin.Configuration.MenuPublish.List.SearchMenuPublishStatus"] = "Stare de publicare",
            ["Admin.Configuration.MenuPublish.List.SearchStoreName"] = "Nume magazin",
            ["admin.configuration.menupublish.completedat"] = "Finalizat la (UTC)",
            ["admin.configuration.menupublish.details"] = "Detalii",
            ["admin.configuration.menupublish.receivedat"] = "Primit la (UTC)",
            ["admin.configuration.menupublish.status"] = "Stare",
            ["admin.configuration.dinein.legacynoloenterpriseqrcodehash"] = "Hash cod QR Nolo Enterprise (moștenire)",
            ["admin.configuration.mgs.backtolist"] = "Back to the list of modifiers group selector",
            ["admin.configuration.settings.generalcommon.blocktitle.googleapi"] = "Cheie GoogleApi",
            ["admin.configuration.settings.geolocation"] = "Geolocație",
            ["admin.configuration.settings.geolocation.blocktitle.distanceradius"] = "Raza distanței",
            ["admin.configuration.settings.geolocation.blocktitle.locationdetection"] = "Detectarea locației",
            ["admin.configuration.settings.kitchencapacity"] = "Capacitatea bucătăriei",
            ["admin.configuration.settings.kitchencapacity.blocktitle.timeslotcapacity"] =
                "Capacitatea intervalului de timp",
            ["admin.configuration.settings.shoppingcart.displaymenuafteraddingproduct"] =
                "Afișează meniul după adăugarea unui produs",
            ["admin.configuration.settings.shoppingcart.displaymenuafteraddingproduct.hint"] =
                "Dacă este bifat, un client va fi dus la pagina de meniu imediat după ce a adăugat un produs în coșul său. Dacă nu este bifată, un client va rămâne pe aceeași pagină din care produsul a fost adăugat în coș.",
            ["admin.configuration.settings.storescope.hint"] =
                "Setările „Toate magazinele” nu sunt afișate la selectarea unui singur magazin",
            ["admin.configuration.spa"] = "Disponibilitate programată a produsului",
            ["admin.configuration.stores.blocktitle.IdleTime"] = "Timp inactiv",
            ["admin.configuration.stores.blocktitle.holiday"] = "Program de deschidere sezonier",
            ["admin.configuration.stores.blocktitle.info"] = "Informații despre magazin",
            ["admin.configuration.stores.blocktitle.selectday"] = "Selectați zile lucrătoare",
            ["admin.configuration.stores.blocktitle.storepickup"] = "Ridicare din magazin",
            ["admin.configuration.stores.blocktitle.storetimings"] = "Orele de deschidere și închidere a magazinului",
            ["admin.configuration.stores.fields.IdleTime"] = "Timp inactiv (min)",
            ["admin.configuration.stores.fields.IdleTime.hint"] = "Timp de inactivitate (min)",
            ["admin.grouporders"] = "Comenzi de grup",
            ["checkout.customerinformation.saveaddress"] = "Save address",
            ["checkout.orderdetails.table.address"] = "Adresa magazinului",
            ["clickandcollect.backtolocation"] = "Înapoi",
            ["clickandcollect.maintitle"] = "CÂND VREI",
            ["clickandcollect.note"] =
                "Notă: intervalele de timp de colectare se pot modifica în timpul procesului de comandă, intervalul de livrare real va fi confirmat în timpul plății.",
            ["clickandcollect.searchtitle"] = "Faceți clic și colectați de la",
            ["clickandcollect.searchtitle.FiveguysUK"] = "Collect from",
            ["clickandcollect.searchtitle.FiveguysDE"] = "Collect from",
            ["clickandcollect.searchtitle.chikn"] = "Collect from",
            ["clickandcollect.startorder"] = "ÎNCEPE COMANDA",
            ["clickandcollect.startorder.FiveguysUK"] = "ORDER MY FOOD",
            ["clickandcollect.startorder.FiveguysDE"] = "ORDER MY FOOD",
            ["clickandcollect.startorder.chikn"] = "ORDER MY FOOD",
            ["clickandcollect.subtitle"] = "SA COLECTE?",
            ["clickandcollect.updatemaintitle"] = "VĂ rugăm SELECTAȚI UN NOU",
            ["clickandcollect.updateorder"] = "ACTUALIZAȚI COMANDA",
            ["clickandcollect.updatesearchtitle"] =
                "Intervalul dvs. orar anterior nu mai este disponibil <br/> coșul dvs. rămâne salvat",
            ["clickandcollect.updatesubtitle"] = "ORA DE COLECTARE",
            ["countrySelector.NotAvailable"] = "Country Selector Not Available",
            ["countrySelector.chooseYourLocation"] = "Alegeți locația dvs",
            ["findpostcode.enterpostcode"] = "Vă rugăm să introduceți codul poștal sau zona de mai jos",
            ["findpostcode.error"] = "Există o problemă în browserul dvs. actual pentru a obține locația geografică.",
            ["findpostcode.findpostcodebutton"] = "GAȚI",
            ["findpostcode.findpostcodebutton.FiveguysUK"] = "Find my five guys",
            ["findpostcode.findpostcodebutton.FiveguysDE"] = "Find my five guys",
            ["findpostcode.findpostcodebutton.TacobellUK"] = "GAȚI",
            ["findpostcode.findpostcodeinputplaceholder"] = "Enter your postcode or area",
            ["findpostcode.mainsubtitle"] = " RESTAURANT",
            ["findpostcode.mainsubtitle.chikn"] = "S",
            ["findpostcode.maintitle"] = "Găsește-ți localul",
            ["findpostcode.notfoundmessage"] = "Ne pare rău. Din păcate, nu putem găsi restaurante în apropiere.",
            ["findpostcode.okbutton"] = "OK",
            ["findpostcode.permissiondenied"] =
                "Acest site web nu are permisiunea de a utiliza API-ul de localizare geografică",
            ["findpostcode.permissiondeniedtimeout"] =
                "Poziția curentă nu a putut fi determinată în perioada de expirare specificată.",
            ["findpostcode.positionunavailable"] = "Poziția actuală nu a putut fi determinată.",
            ["findpostcode.searching"] = "Se caută...",
            ["findpostcode.searchmaintitle"] = "Să începem",
            ["findpostcode.searchmaintitle.Fiveguys"] = "Skip the queue, <br/> order online",
            ["findpostcode.searchmaintitle.FiveguysUK"] = "Skip the queue, <br/> order online",
            ["findpostcode.searchmaintitle.FiveguysDE"] = "Skip the queue, <br/> order online",
            ["findpostcode.storeisnowdisabled"] =
                "Ne pare rău, dar acest magazin nu mai este acum disponibil pentru comandă online.",
            ["findpostcode.usecurrentlocation"] = "sau folosiți locația mea",
            ["findpostcode.usecurrentlocation.TacobellUK"] = "sau folosiți locația mea",
            ["findpostcode.validation"] = "Vă rugăm să introduceți un cod poștal sau o zonă validă",
            ["groupordering.cancelgrouporder"] = "Anulați comanda de grup",
            ["groupordering.cancelgrouporder.question"] = "Anulați comanda de grup?",
            ["groupordering.cancelgrouporder.question.subtitle"] =
                "Dacă anulați această comandă, invitații dvs. și articolele lor vor fi eliminați.",
            ["groupordering.cancelgrouporder.byowner"] = "Coșul de grup a fost anulat de proprietar",
            ["groupordering.closegrouporder.byowner"] =
                "Coșul de grup a fost închis de proprietar, nu mai puteți face modificări la comandă.",
            ["groupordering.keeporder"] = "Păstrați comanda",
            ["GroupOrdering.YouHaveLeft"] = "Ați părăsit comanda de grup",
            ["invalidAddress.deliverynotpossible"] = "Nu livrăm în această zonă.",
            ["invalidAddress.okbutton"] = "OK",
            ["limiteditemswereremoved.modalbody"] =
                "Unele articole nu mai sunt disponibile pentru acest interval orar și au fost eliminate din coș.",
            ["limiteditemswereremoved.modalmaintitle"] = "Au fost eliminate unele articole cu durată limitată",
            ["marketplace.modalmaintitle"] = "Opțiuni de livrare",
            ["order.order#"] = "#",
            ["review.product.selectrating"] = "Selectați o evaluare",
            ["store.slottime"] = "(cel mai devreme)",
            ["storeselection.backbutton"] = "Înapoi",
            ["storeselection.changelocation"] = "Change",
            ["storeselection.clickandcollect"] = "CLICK & COLECTA",
            ["storeselection.clickandcollect.FiveguysUK"] = "COLECTA",
            ["storeselection.clickandcollect.FiveguysDE"] = "COLECTA",
            ["storeselection.clickandcollect.chikn"] = "COLECTA",
            ["storeselection.clickandcollectPlus"] = "COLECTA+",
            ["storeselection.closed"] = "ÎNCHIS",
            ["storeselection.curbside"] = "RIDICARE DIN BORDURA",
            ["storeselection.delivery"] = "LIVRARE",
            ["storeselection.deliverymarketplace"] = "Livrare din ",
            ["storeselection.findbutton"] = "GAȚI",
            ["storeselection.moreinfo"] = "Mai multe informații",
            ["storeselection.nearrestaurant"] = "restaurant din apropierea acestei locații",
            ["storeselection.nearrestaurant.chikn"] = "chicken shop closest to you",
            ["storeselection.nearrestaurants"] = "restaurante din apropierea acestei locații",
            ["storeselection.nearrestaurants.FiveguysUK"] = "Restaurants closest to your location",
            ["storeselection.nearrestaurants.FiveguysDE"] = "Restaurants closest to your location",
            ["storeselection.nearrestaurants.chikn"] = "chicken shops closest to you",
            ["storeselection.open"] = "Deschide",
            ["storeselection.orderfrom"] = "Sau comanda de la",
            ["storeselection.title.FiveguysUK"] = "Your closest five guys",
            ["storeselection.title.FiveguysDE"] = "Your closest five guys",
            ["storeselection.title.WagamamaUK"] = "Cel mai apropiat Wagamama al tău",
            ["timeSlotSelection.ReservationNotAllowed"] =
                "Intervalul orar selectat nu este disponibil <br/> Vă rugăm să selectați altul",
            ["timeSlotSelection.reservationTimedOut"] = "Rezervarea dvs. a expirat <br/> coșul dvs. rămâne salvat",
            ["TimeSlotSelection.NoSlotsForSelectedDay"] =
                "Nu există intervale orare disponibile pentru ziua selectată.",
            ["ProductInfo.NutritionTableUnit.0"] = "Valoare nutritivă",
            ["ProductInfo.NutritionTableUnit.1"] = "Valoare nutritivă per unitate",
            ["ProductInfo.NutritionTableUnit.2"] = "Valoare nutritivă pentru 100 ml",
            ["ProductInfo.NutritionTableUnit.3"] = "Valoare nutritivă pentru 100 g",
            ["ProductInfo.SalesName"] = "Nume comercial",
            ["ProductInfo.Additives"] = "Aditivi",
            ["ProductInfo.Ingredients"] = "Ingredient",
            ["ProductInfo.Manufacturer"] = "Fabricant",
            ["Settings.AnalyticsSettings.Edit"] = "Setările de analiză au fost editate.",
            ["Admin.Configuration.Settings.Analytics.GoogleTagManagerId"] = "ID Google Tag Manager",
            ["Admin.Configuration.Settings.Analytics.GoogleTagManagerActive"] =
                "Activează urmărirea încorporată Google Tag Manager",
            ["Admin.Configuration.Settings.Analytics.GoogleTagManagerEcommerceTrackingActive"] =
                "Suport Google Tag Manager Ecommerce",
            ["Admin.Configuration.Settings.Analytics"] = "Analytics",
            ["Admin.Config.Analytics.GoogleTagManager"] = "Google Tag Manager"
        };
    }

    public async Task AddLocalizations(ILocalizationService localizationService, int languageId)
    {
        await localizationService.AddOrUpdateLocaleResourceAsync(GetTerms(), languageId);
    }
}